package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/tty00a381/anybot/app/host"
)

func TestRunInitDoctorAndPlugins(t *testing.T) {
	dir := t.TempDir()
	out, errOut, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"init", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "已初始化 AnyBot 工作目录") ||
		!strings.Contains(out.String(), "anybot doctor") ||
		!strings.Contains(out.String(), "anybot up") {
		t.Fatalf("init output:\n%s", out.String())
	}
	out.Reset()
	errOut.Reset()
	config := filepath.Join(dir, "anybot.yaml")
	data, err := os.ReadFile(config)
	if err != nil {
		t.Fatal(err)
	}
	data = []byte(strings.ReplaceAll(string(data), `listen: "127.0.0.1:6700"`, `listen: "127.0.0.1:0"`))
	if err := os.WriteFile(config, data, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := run([]string{"doctor", "-config", config}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "传输：reverse_ws") || !strings.Contains(out.String(), "插件：help") {
		t.Fatalf("doctor output:\n%s", out.String())
	}
	if errOut.Len() != 0 {
		t.Fatalf("doctor stderr:\n%s", errOut.String())
	}
	for _, name := range []string{host.PluginWorkspaceFile, "plugins.gen.go", "main.go", "go.mod", "plugins.d"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Fatalf("%s was not generated: %v", name, err)
		}
	}

	out.Reset()
	if err := run([]string{"plugins"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "help\t1.0.0") || !strings.Contains(out.String(), "echo\t1.0.0") {
		t.Fatalf("plugins output:\n%s", out.String())
	}
}

func TestRunInitRejectsUnmanagedGeneratedFilesWithoutPartialWrite(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte("package main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"init", "-dir", dir})
	if err == nil {
		t.Fatal("init should reject unmanaged main.go")
	}
	if !strings.Contains(err.Error(), "不是 anybot 生成文件") {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "anybot.yaml")); !os.IsNotExist(err) {
		t.Fatalf("anybot.yaml should not be partially written: %v", err)
	}
}

func TestRunInitForceTakesOverGeneratedWorkspaceFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte("package main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run([]string{"init", "-dir", dir, "-force"}); err != nil {
		t.Fatal(err)
	}
	mainGo := readTestFile(t, filepath.Join(dir, "main.go"))
	if !strings.Contains(mainGo, "Code generated by anybot") ||
		!strings.Contains(mainGo, "registerExternalPlugins(registry)") {
		t.Fatalf("main.go:\n%s", mainGo)
	}
}

func TestRunVersionAndHelp(t *testing.T) {
	old := version
	version = "v9.9.9"
	defer func() { version = old }()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"version"}); err != nil {
		t.Fatal(err)
	}
	if got := out.String(); got != "anybot v9.9.9\n" {
		t.Fatalf("version output = %q", got)
	}
	out.Reset()
	if err := run([]string{"help"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "anybot run") || !strings.Contains(out.String(), "anybot plugins") {
		t.Fatalf("help output:\n%s", out.String())
	}
	out.Reset()
	if err := run([]string{"dev"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "anybot dev init") || !strings.Contains(out.String(), "anybot dev plugin") {
		t.Fatalf("dev help output:\n%s", out.String())
	}
	out.Reset()
	if err := run([]string{"dev", "help"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "anybot dev doctor") || !strings.Contains(out.String(), "anybot dev run") {
		t.Fatalf("dev help output:\n%s", out.String())
	}
	out.Reset()
	if err := run([]string{"plugin"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "anybot plugin add") ||
		!strings.Contains(out.String(), "anybot plugin status") ||
		!strings.Contains(out.String(), "anybot plugin inspect") {
		t.Fatalf("plugin help output:\n%s", out.String())
	}
	out.Reset()
	if err := run([]string{"plugin", "help"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "anybot plugin enable") ||
		!strings.Contains(out.String(), "anybot plugin disable") ||
		!strings.Contains(out.String(), "anybot plugin inspect") {
		t.Fatalf("plugin help output:\n%s", out.String())
	}
}

func TestRunDevInitPluginAndDoctor(t *testing.T) {
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"dev", "init", "-dir", dir, "-module", "example.com/devbot"}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "已生成 core 项目") ||
		!strings.Contains(out.String(), "anybot dev doctor") ||
		!strings.Contains(out.String(), "go run .") {
		t.Fatalf("dev init output:\n%s", out.String())
	}
	out.Reset()
	if _, err := os.Stat(filepath.Join(dir, "core.yaml")); err != nil {
		t.Fatal(err)
	}
	mainGo := readTestFile(t, filepath.Join(dir, "main.go"))
	if !strings.Contains(mainGo, `"github.com/tty00a381/anybot/core"`) {
		t.Fatalf("main.go:\n%s", mainGo)
	}

	config := filepath.Join(dir, "core.yaml")
	data := readTestFile(t, config)
	data = strings.ReplaceAll(data, `listen: "127.0.0.1:6700"`, `listen: "127.0.0.1:0"`)
	if err := os.WriteFile(config, []byte(data), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run([]string{"dev", "doctor", "-config", config}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "传输：reverse_ws") {
		t.Fatalf("dev doctor output:\n%s", out.String())
	}
	out.Reset()

	if err := run([]string{"dev", "plugin", "hello-world", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "已生成插件骨架：hello_world") ||
		!strings.Contains(out.String(), "go test ./...") {
		t.Fatalf("dev plugin output:\n%s", out.String())
	}
	plugin := readTestFile(t, filepath.Join(dir, "plugins", "hello_world", "hello_world.go"))
	if !strings.Contains(plugin, "var Module = absdk.Define") ||
		!strings.Contains(plugin, "absdk.EventContext") ||
		strings.Contains(plugin, `"github.com/tty00a381/anybot/core"`) {
		t.Fatalf("plugin scaffold:\n%s", plugin)
	}
	out.Reset()

	if err := run([]string{"dev", "plugin", "-template", "minecraft", "mc-admin", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	mcPlugin := readTestFile(t, filepath.Join(dir, "plugins", "mc_admin", "mc_admin.go"))
	if !strings.Contains(mcPlugin, "RequireAdmin") || !strings.Contains(mcPlugin, "ctx.DataDir()") {
		t.Fatalf("minecraft plugin scaffold:\n%s", mcPlugin)
	}
}

func TestRunDevPluginStandalone(t *testing.T) {
	root := t.TempDir()
	anybotDir := filepath.Join(root, "anybot")
	setTestFrameworkDependencies(t, []moduleDependency{
		{Module: "github.com/tty00a381/anybot", Version: "v0.0.0", Replace: anybotDir},
	})
	dir := filepath.Join(root, "weather")
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{
		"dev", "plugin", "daily-weather",
		"-dir", dir,
		"-module", "github.com/acme/anybot-weather",
	}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "已生成独立插件模块：daily_weather (github.com/acme/anybot-weather)") ||
		!strings.Contains(out.String(), "go test ./...") ||
		!strings.Contains(out.String(), "anybot plugin add github.com/acme/anybot-weather -name daily_weather -replace "+dir) ||
		!strings.Contains(out.String(), "anybot plugin enable daily_weather") {
		t.Fatalf("dev plugin output:\n%s", out.String())
	}
	goMod := readTestFile(t, filepath.Join(dir, "go.mod"))
	if !strings.Contains(goMod, "module github.com/acme/anybot-weather") ||
		!strings.Contains(goMod, "require github.com/tty00a381/anybot v0.0.0") ||
		!strings.Contains(goMod, "replace github.com/tty00a381/anybot => ../anybot") {
		t.Fatalf("go.mod:\n%s", goMod)
	}
	plugin := readTestFile(t, filepath.Join(dir, "daily_weather.go"))
	if !strings.Contains(plugin, `absdk.Manifest{Name: "daily_weather"`) ||
		strings.Contains(plugin, `"github.com/tty00a381/anybot/core"`) {
		t.Fatalf("plugin scaffold:\n%s", plugin)
	}
	readme := readTestFile(t, filepath.Join(dir, "README.md"))
	if !strings.Contains(readme, "anybot plugin add github.com/acme/anybot-weather -name daily_weather -replace <插件目录>") {
		t.Fatalf("README.md:\n%s", readme)
	}
}

func TestRunDevPluginTemplateFlagForms(t *testing.T) {
	tests := []struct {
		name     string
		args     []string
		path     string
		contains string
	}{
		{
			name:     "after name",
			args:     []string{"dev", "plugin", "buddy", "-template", "companion"},
			path:     filepath.Join("plugins", "buddy", "buddy.go"),
			contains: "renderCompanionReply",
		},
		{
			name:     "before name",
			args:     []string{"dev", "plugin", "-template", "companion", "buddy"},
			path:     filepath.Join("plugins", "buddy", "buddy.go"),
			contains: "renderCompanionReply",
		},
		{
			name:     "equals after name",
			args:     []string{"dev", "plugin", "mc-admin", "--template=minecraft"},
			path:     filepath.Join("plugins", "mc_admin", "mc_admin.go"),
			contains: "writeFileAtomic",
		},
		{
			name:     "equals before name",
			args:     []string{"dev", "plugin", "--template=minecraft", "mc-admin"},
			path:     filepath.Join("plugins", "mc_admin", "mc_admin.go"),
			contains: "writeFileAtomic",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			args := append([]string{}, tt.args...)
			args = append(args, "-dir", dir)
			if err := run(args); err != nil {
				t.Fatal(err)
			}
			plugin := readTestFile(t, filepath.Join(dir, tt.path))
			if !strings.Contains(plugin, tt.contains) {
				t.Fatalf("plugin scaffold:\n%s", plugin)
			}
		})
	}
}

func TestRunDevPluginTemplateFlagErrors(t *testing.T) {
	if err := run([]string{"dev", "plugin", "broken", "-dir", t.TempDir(), "-template"}); err == nil || !strings.Contains(err.Error(), "-template 需要值") {
		t.Fatalf("missing template value err = %v", err)
	}
	if err := run([]string{"dev", "plugin", "broken", "-dir", t.TempDir(), "-template", "ghost"}); err == nil || !strings.Contains(err.Error(), "未知插件模板") {
		t.Fatalf("unknown template err = %v", err)
	}
}

func TestRunDevPluginStandaloneReleaseVersion(t *testing.T) {
	setTestFrameworkDependencies(t, releaseFrameworkDependencies("v1.2.3"))
	dir := filepath.Join(t.TempDir(), "space dir", "weather")
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{
		"dev", "plugin", "daily-weather",
		"-dir", dir,
		"-module", "github.com/acme/anybot-weather",
	}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "go mod tidy") ||
		!strings.Contains(out.String(), shellQuote(dir)) {
		t.Fatalf("dev plugin output:\n%s", out.String())
	}
	goMod := readTestFile(t, filepath.Join(dir, "go.mod"))
	if !strings.Contains(goMod, "require github.com/tty00a381/anybot v1.2.3") ||
		strings.Contains(goMod, "replace github.com/tty00a381/anybot") {
		t.Fatalf("go.mod:\n%s", goMod)
	}
	if _, err := os.Stat(filepath.Join(dir, "go.sum")); !os.IsNotExist(err) {
		t.Fatalf("go.sum should not be generated without local replace: %v", err)
	}
}

func TestRunDevPluginStandaloneRejectsUnknownFrameworkDependency(t *testing.T) {
	setTestFrameworkDependencies(t, []moduleDependency{{Module: "github.com/tty00a381/anybot", Version: "v0.0.0"}})
	err := run([]string{
		"dev", "plugin", "daily-weather",
		"-dir", t.TempDir(),
		"-module", "github.com/acme/anybot-weather",
	})
	if err == nil || !strings.Contains(err.Error(), "生成独立插件需要可解析的 AnyBot 版本") {
		t.Fatalf("err = %v", err)
	}
}

func TestRunDoctorWarnsForPublicReverseWSWithoutToken(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte(`runtime:
  log_level: info
adapter:
  protocol: onebot11
  transport:
    type: reverse_ws
    listen: "0.0.0.0:0"
plugins: {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	out, errOut, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"doctor", "-config", config}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "配置可用") {
		t.Fatalf("doctor output:\n%s", out.String())
	}
	if !strings.Contains(errOut.String(), "反向 WebSocket 监听非本机地址") {
		t.Fatalf("doctor stderr:\n%s", errOut.String())
	}
}

func TestRunDevDoctorWarnsForMissingOutboundTokenEnv(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "core.yaml")
	if err := os.WriteFile(config, []byte(`protocol: onebot11
transport:
  type: websocket
  url: "ws://127.0.0.1:6700/"
  access_token_env: ANYBOT_TEST_MISSING_TOKEN
`), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("ANYBOT_TEST_MISSING_TOKEN", "")
	_, errOut, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"dev", "doctor", "-config", config}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(errOut.String(), "ANYBOT_TEST_MISSING_TOKEN 未设置") {
		t.Fatalf("dev doctor stderr:\n%s", errOut.String())
	}
}

func TestRunPluginAddAndList(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.2.3", nil
	})
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather", "-symbol", "Weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已添加：weather (github.com/acme/weather@v1.2.3.Weather)") ||
		!strings.Contains(out.String(), "配置已添加：weather") ||
		!strings.Contains(out.String(), "下一步：") ||
		!strings.Contains(out.String(), "cd "+dir) ||
		!strings.Contains(out.String(), "anybot plugin enable weather") ||
		!strings.Contains(out.String(), "anybot up") {
		t.Fatalf("add output:\n%s", out.String())
	}
	if _, err := os.Stat(filepath.Join(dir, "plugins.gen.go")); err != nil {
		t.Fatal(err)
	}
	config := readTestFile(t, filepath.Join(dir, "anybot.yaml"))
	if strings.Contains(config, "weather:") {
		t.Fatalf("config:\n%s", config)
	}
	pluginConfig := readTestFile(t, filepath.Join(dir, "plugins.d", "weather.yaml"))
	if !strings.Contains(pluginConfig, "enabled: false") || !strings.Contains(pluginConfig, "config: {}") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "version: v1.2.3") {
		t.Fatalf("manifest:\n%s", manifest)
	}
	out.Reset()
	if err := run([]string{"plugin", "list", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "weather\tgithub.com/acme/weather@v1.2.3\tWeather") {
		t.Fatalf("list output:\n%s", out.String())
	}
}

func TestRunPluginAddWithReplaceDoesNotResolveLatest(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		t.Fatalf("local replace should not resolve %s@%s", module, query)
		return "", nil
	})
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	root := t.TempDir()
	dir := filepath.Join(root, "bot")
	pluginDir := filepath.Join(root, "weather")
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather", "-replace", pluginDir, "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -require=github.com/acme/weather@v0.0.0",
		dir + " go mod edit -replace=github.com/acme/weather=../weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "插件已添加：weather (github.com/acme/weather => ../weather.Module)") {
		t.Fatalf("add output:\n%s", out.String())
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if strings.Contains(manifest, "version:") || !strings.Contains(manifest, "replace: ../weather") {
		t.Fatalf("manifest:\n%s", manifest)
	}
}

func TestRunPluginAddWithReplaceUsesPathMajorPlaceholder(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		t.Fatalf("local replace should not resolve %s@%s", module, query)
		return "", nil
	})
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	root := t.TempDir()
	dir := filepath.Join(root, "bot")
	pluginDir := filepath.Join(root, "weather")
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather/v2", "-replace", pluginDir, "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -require=github.com/acme/weather/v2@v2.0.0",
		dir + " go mod edit -replace=github.com/acme/weather/v2=../weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "插件已添加：weather (github.com/acme/weather/v2 => ../weather.Module)") {
		t.Fatalf("add output:\n%s", out.String())
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "name: weather") ||
		strings.Contains(manifest, "version:") ||
		!strings.Contains(manifest, "module: github.com/acme/weather/v2") {
		t.Fatalf("manifest:\n%s", manifest)
	}
}

func TestRunPluginAddReportsVersionResolutionErrorWithoutPartialWrite(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "", errors.New("module not found")
	})
	dir := t.TempDir()
	err := run([]string{"plugin", "add", "github.com/acme/weather", "-dir", dir})
	if err == nil {
		t.Fatal("version resolution failure should reject plugin add")
	}
	if !strings.Contains(err.Error(), "解析插件版本 github.com/acme/weather@latest 失败") ||
		!strings.Contains(err.Error(), "module not found") {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, host.PluginWorkspaceFile)); !os.IsNotExist(err) {
		t.Fatalf("workspace should not be created, err=%v", err)
	}
}

func TestRunPluginAddSupportsVersionAndReplace(t *testing.T) {
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	root := t.TempDir()
	dir := filepath.Join(root, "bot")
	pluginDir := filepath.Join(root, "weather")
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather@v1.2.3", "-replace", pluginDir, "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -require=github.com/acme/weather@v1.2.3",
		dir + " go mod edit -replace=github.com/acme/weather=../weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "插件已添加：weather (github.com/acme/weather@v1.2.3 => ../weather.Module)") {
		t.Fatalf("add output:\n%s", out.String())
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "version: v1.2.3") || !strings.Contains(manifest, "replace: ../weather") {
		t.Fatalf("manifest:\n%s", manifest)
	}
}

func TestRunPluginUpdatePreservesConfigAndSyncsGoMod(t *testing.T) {
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	root := t.TempDir()
	dir := filepath.Join(root, "bot")
	pluginDir := filepath.Join(root, "weather")
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather@v1.2.3", "-replace", pluginDir, "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	pluginConfig := filepath.Join(dir, "plugins.d", "weather.yaml")
	if err := os.WriteFile(pluginConfig, []byte("enabled: true\nconfig:\n  city: Hangzhou\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	calls = nil
	out.Reset()
	if err := run([]string{"plugin", "update", "weather", "-version", "v1.3.0", "-clear-replace", "-symbol", "Weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -require=github.com/acme/weather@v1.3.0",
		dir + " go mod edit -dropreplace=github.com/acme/weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "插件已更新：weather (github.com/acme/weather@v1.3.0.Weather)") {
		t.Fatalf("update output:\n%s", out.String())
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "version: v1.3.0") ||
		strings.Contains(manifest, "replace:") ||
		!strings.Contains(manifest, "symbol: Weather") {
		t.Fatalf("manifest:\n%s", manifest)
	}
	if config := readTestFile(t, pluginConfig); !strings.Contains(config, "city: Hangzhou") {
		t.Fatalf("plugin config should be preserved:\n%s", config)
	}
}

func TestRunPluginUpdatePinsLatestBeforeWriting(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.4.0", nil
	})
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	dir := t.TempDir()
	if _, err := host.AddPluginModule(host.AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather",
		Version: "v1.2.3",
	}); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "update", "weather", "-version", "latest", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -require=github.com/acme/weather@v1.4.0",
		dir + " go mod edit -dropreplace=github.com/acme/weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "插件已更新：weather (github.com/acme/weather@v1.4.0.Module)") {
		t.Fatalf("update output:\n%s", out.String())
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "version: v1.4.0") || strings.Contains(manifest, "latest") {
		t.Fatalf("manifest:\n%s", manifest)
	}
}

func TestRunPluginUpdateClearReplacePinsLatest(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.4.0", nil
	})
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	dir := t.TempDir()
	if _, err := host.AddPluginModule(host.AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather",
		Replace: "../weather",
	}); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "update", "weather", "-clear-replace", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -require=github.com/acme/weather@v1.4.0",
		dir + " go mod edit -dropreplace=github.com/acme/weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "插件已更新：weather (github.com/acme/weather@v1.4.0.Module)") {
		t.Fatalf("update output:\n%s", out.String())
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "version: v1.4.0") ||
		strings.Contains(manifest, "replace:") {
		t.Fatalf("manifest:\n%s", manifest)
	}
}

func TestRunPluginUpdateVersionResolutionErrorDoesNotWrite(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "", errors.New("module not found")
	})
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	commandRunner = func(dir, name string, args ...string) error {
		t.Fatalf("go command should not run after resolution failure: %s %s", name, strings.Join(args, " "))
		return nil
	}
	dir := t.TempDir()
	if _, err := host.AddPluginModule(host.AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather",
		Version: "v1.2.3",
	}); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"plugin", "update", "weather", "-version", "latest", "-dir", dir})
	if err == nil {
		t.Fatal("version resolution failure should reject plugin update")
	}
	if !strings.Contains(err.Error(), "解析插件版本 github.com/acme/weather@latest 失败") ||
		!strings.Contains(err.Error(), "module not found") {
		t.Fatalf("err = %v", err)
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if !strings.Contains(manifest, "version: v1.2.3") ||
		strings.Contains(manifest, "latest") {
		t.Fatalf("manifest should remain unchanged:\n%s", manifest)
	}
}

func TestPluginVersionNeedsResolution(t *testing.T) {
	tests := []struct {
		module  string
		version string
		want    bool
	}{
		{module: "github.com/acme/weather", version: "", want: true},
		{module: "github.com/acme/weather", version: "latest", want: true},
		{module: "github.com/acme/weather", version: "main", want: true},
		{module: "github.com/acme/weather", version: "abcdef123456", want: true},
		{module: "github.com/acme/weather", version: "v1", want: true},
		{module: "github.com/acme/weather", version: "v1.2", want: true},
		{module: "github.com/acme/weather", version: "v1.2.x", want: true},
		{module: "github.com/acme/weather", version: "v1.2.3foo", want: true},
		{module: "github.com/acme/weather", version: "v1.2.3", want: false},
		{module: "github.com/acme/weather", version: "v1.2.3-rc.1", want: false},
		{module: "github.com/acme/weather", version: "v1.2.3+build.1", want: false},
		{module: "github.com/acme/weather", version: "v0.0.0-20260101000000-abcdefabcdef", want: false},
		{module: "github.com/acme/weather", version: "v2.0.0+incompatible", want: false},
		{module: "github.com/acme/weather/v2", version: "v2.0.0", want: false},
		{module: "github.com/acme/weather/v2", version: "v1.2.3", want: true},
		{module: "github.com/acme/weather/v2", version: "v2", want: true},
		{module: "github.com/acme/weather/v2", version: "v2.0", want: true},
	}
	for _, tt := range tests {
		t.Run(tt.module+"@"+tt.version, func(t *testing.T) {
			if got := pluginVersionNeedsResolution(tt.module, tt.version); got != tt.want {
				t.Fatalf("pluginVersionNeedsResolution(%q, %q) = %v, want %v", tt.module, tt.version, got, tt.want)
			}
		})
	}
}

func TestNormalizeReplacePath(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "bot")
	pluginDir := filepath.Join(root, "plugins", "weather")
	got, err := normalizeReplacePath(dir, pluginDir)
	if err != nil {
		t.Fatal(err)
	}
	if got != "../plugins/weather" {
		t.Fatalf("replace = %q", got)
	}
}

func TestRunPluginAddRejectsBuiltinNameCollision(t *testing.T) {
	dir := t.TempDir()
	err := run([]string{"plugin", "add", "github.com/acme/help", "-dir", dir})
	if err == nil {
		t.Fatal("builtin name collision should be rejected")
	}
	if !strings.Contains(err.Error(), `插件名 "help" 已被内置插件占用`) ||
		!strings.Contains(err.Error(), "-name") {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, host.PluginWorkspaceFile)); !os.IsNotExist(err) {
		t.Fatalf("workspace should not be created, err=%v", err)
	}
}

func TestRunPluginAddAllowsRenamingBuiltinCollision(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/help" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.2.3", nil
	})
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/help", "-name", "acme_help", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已添加：acme_help") {
		t.Fatalf("add output:\n%s", out.String())
	}
}

func TestRunPluginStatus(t *testing.T) {
	dir := t.TempDir()
	if err := run([]string{"init", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if _, err := host.AddPluginModule(host.AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, err := host.EnsurePluginConfigEntry(filepath.Join(dir, "anybot.yaml"), "weather"); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "status", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "名称\t来源\t配置\t启用\t可加载\t版本\t模块") ||
		!strings.Contains(out.String(), "help\t内置\t是\t是\t是\t1.0.0\t-") ||
		!strings.Contains(out.String(), "weather\t外部\t是\t否\t否\t-\tgithub.com/acme/weather") {
		t.Fatalf("status output:\n%s", out.String())
	}
}

func TestRunPluginInspect(t *testing.T) {
	dir := t.TempDir()
	if err := run([]string{"init", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "inspect", "help", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "名称：help") ||
		!strings.Contains(out.String(), "配置文件："+filepath.Join(dir, "anybot.yaml")) ||
		!strings.Contains(out.String(), "当前配置：") ||
		!strings.Contains(out.String(), "默认配置：") ||
		!strings.Contains(out.String(), "command: help") {
		t.Fatalf("inspect output:\n%s", out.String())
	}
}

func TestRunPluginCheck(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte(`plugins:
  help:
    enabled: true
    config: {}
  legacy:
    enabled: false
    config: {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "check", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "名称\t来源\t状态\t说明") ||
		!strings.Contains(out.String(), "help\t内置\t可用\t-") ||
		!strings.Contains(out.String(), "legacy\t配置\t禁用\t-") {
		t.Fatalf("check output:\n%s", out.String())
	}

	out.Reset()
	if err := os.WriteFile(config, []byte(`plugins:
  ratelimit:
    enabled: true
    config:
      limit: 0
      window: 1m
`), 0o644); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"plugin", "check", "-dir", dir})
	if err == nil || !strings.Contains(err.Error(), "插件配置检查失败") {
		t.Fatalf("err = %v", err)
	}
	if !strings.Contains(out.String(), "ratelimit\t内置\t无效") ||
		!strings.Contains(out.String(), "ratelimit.limit") {
		t.Fatalf("invalid check output:\n%s", out.String())
	}
}

func TestRunPluginRemove(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.2.3", nil
	})
	dir := t.TempDir()
	if err := run([]string{"plugin", "add", "github.com/acme/weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "remove", "weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已移除：weather") ||
		!strings.Contains(out.String(), "配置已移除：weather") {
		t.Fatalf("remove output:\n%s", out.String())
	}
	config := readTestFile(t, filepath.Join(dir, "anybot.yaml"))
	if strings.Contains(config, "weather:") {
		t.Fatalf("config:\n%s", config)
	}
	if _, err := os.Stat(filepath.Join(dir, "plugins.d", "weather.yaml")); !os.IsNotExist(err) {
		t.Fatalf("plugin config should be removed: %v", err)
	}
	manifest := readTestFile(t, filepath.Join(dir, host.PluginWorkspaceFile))
	if strings.Contains(manifest, "github.com/acme/weather") {
		t.Fatalf("manifest:\n%s", manifest)
	}
}

func TestRunPluginRemoveDropsVersionedGoModEntries(t *testing.T) {
	dir := t.TempDir()
	if _, err := host.AddPluginModule(host.AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather",
		Version: "v1.2.3",
		Replace: "../weather",
	}); err != nil {
		t.Fatal(err)
	}
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins:\n  weather:\n    enabled: false\n    config: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	if err := run([]string{"plugin", "remove", "weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		dir + " go mod edit -droprequire=github.com/acme/weather",
		dir + " go mod edit -dropreplace=github.com/acme/weather",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
}

func TestRunPluginRemoveRejectsBuiltinPlugin(t *testing.T) {
	err := run([]string{"plugin", "remove", "help"})
	if err == nil {
		t.Fatal("builtin plugin remove should be rejected")
	}
	if !strings.Contains(err.Error(), `内置插件 "help" 不能移除`) ||
		!strings.Contains(err.Error(), "plugin disable help") {
		t.Fatalf("err = %v", err)
	}
}

func TestRunPluginSync(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins:\n  echo:\n    enabled: false\n    config: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "sync", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件配置已同步：") {
		t.Fatalf("sync output:\n%s", out.String())
	}
	updated := readTestFile(t, config)
	if !strings.Contains(updated, "command: echo") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginSyncSkipsDisabledUnknownPlugin(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte(`plugins:
  echo:
    enabled: false
    config: {}
  legacy:
    enabled: false
    config: {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "sync", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "未知插件已跳过：legacy（已禁用）") {
		t.Fatalf("sync output:\n%s", out.String())
	}
	updated := readTestFile(t, config)
	if !strings.Contains(updated, "command: echo") || !strings.Contains(updated, "legacy:") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginSyncSkipsExternalWorkspacePlugin(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.2.3", nil
	})
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	out.Reset()
	if err := run([]string{"plugin", "sync", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件配置已同步：") ||
		!strings.Contains(out.String(), "外部插件待构建：weather") {
		t.Fatalf("sync output:\n%s", out.String())
	}
}

func TestRunPluginConfigResetSyncsBuiltinDefaults(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte(`plugins:
  help:
    enabled: true
    config:
      command: docs
      lines:
        - custom
`), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "config", "help", "-reset", "command", "lines", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件配置已重置：help（2 项）") ||
		!strings.Contains(out.String(), "默认配置已同步：1 项更新") {
		t.Fatalf("reset output:\n%s", out.String())
	}
	updated := readTestFile(t, config)
	if !strings.Contains(updated, "command: help") ||
		!strings.Contains(updated, "/help 显示帮助") ||
		strings.Contains(updated, "command: docs") ||
		strings.Contains(updated, "custom") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginConfigResetUsesPluginConfigDir(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	pluginPath := filepath.Join(dir, "plugins.d", "help.yaml")
	if err := os.Mkdir(filepath.Dir(pluginPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(config, []byte("plugin_config_dir: plugins.d\nplugins: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(pluginPath, []byte(`enabled: true
config:
  command: docs
  lines:
    - custom
`), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "config", "help", "-reset", "command", "lines", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件配置已重置：help（2 项）") ||
		!strings.Contains(out.String(), "默认配置已同步：1 项更新") {
		t.Fatalf("reset output:\n%s", out.String())
	}
	updated := readTestFile(t, pluginPath)
	if !strings.Contains(updated, "command: help") ||
		!strings.Contains(updated, "/help 显示帮助") ||
		strings.Contains(updated, "command: docs") ||
		strings.Contains(updated, "custom") {
		t.Fatalf("plugin config:\n%s", updated)
	}
	main := readTestFile(t, config)
	if strings.Contains(main, "command:") || strings.Contains(main, "lines:") {
		t.Fatalf("main config should not receive split config:\n%s", main)
	}
}

func TestRunPluginConfigResetMustFollowPluginName(t *testing.T) {
	err := run([]string{"plugin", "config", "-reset", "command", "help"})
	if err == nil || !strings.Contains(err.Error(), "-reset 必须写在插件名之后") {
		t.Fatalf("err = %v", err)
	}
}

func TestRunPluginConfigResetRejectsMixedSetAndReset(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins:\n  help:\n    enabled: true\n    config: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"plugin", "config", "help", "-reset", "command", "command=docs", "-dir", dir})
	if err == nil || !strings.Contains(err.Error(), "不能同时设置和重置插件配置") {
		t.Fatalf("err = %v", err)
	}
}

func TestRunPluginConfigResetWorkspacePluginWaitsForGeneratedHost(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte(`plugins:
  weather:
    enabled: true
    config:
      city: Hangzhou
      unit: c
`), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := host.AddPluginModule(host.AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "config", "weather", "-reset", "city", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件配置已重置：weather（1 项）") ||
		!strings.Contains(out.String(), "默认配置待构建同步：weather") {
		t.Fatalf("reset output:\n%s", out.String())
	}
	updated := readTestFile(t, config)
	if strings.Contains(updated, "city: Hangzhou") || !strings.Contains(updated, "unit: c") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginEnableDisable(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins:\n  echo:\n    enabled: false\n    config: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "enable", "echo", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已启用：echo") {
		t.Fatalf("enable output:\n%s", out.String())
	}
	if updated := readTestFile(t, config); !strings.Contains(updated, "enabled: true") {
		t.Fatalf("config:\n%s", updated)
	}
	out.Reset()
	if err := run([]string{"plugin", "disable", "echo", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已禁用：echo") {
		t.Fatalf("disable output:\n%s", out.String())
	}
	if updated := readTestFile(t, config); !strings.Contains(updated, "enabled: false") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginEnableSyncsBuiltinDefaults(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "enable", "ratelimit", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已启用：ratelimit") ||
		!strings.Contains(out.String(), "默认配置已同步：1 项更新") {
		t.Fatalf("enable output:\n%s", out.String())
	}
	updated := readTestFile(t, config)
	if !strings.Contains(updated, "ratelimit:") ||
		!strings.Contains(updated, "enabled: true") ||
		!strings.Contains(updated, "limit: 5") ||
		!strings.Contains(updated, "window: 1m") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginEnableRejectsUnknownTarget(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"plugin", "enable", "weathre", "-dir", dir})
	if err == nil {
		t.Fatal("unknown plugin should be rejected")
	}
	if !strings.Contains(err.Error(), "未知插件 \"weathre\"") || !strings.Contains(err.Error(), "plugin add") {
		t.Fatalf("err = %v", err)
	}
	if updated := readTestFile(t, config); strings.Contains(updated, "weathre") {
		t.Fatalf("config was polluted:\n%s", updated)
	}
}

func TestRunPluginEnableRejectsUnknownConfiguredTarget(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins:\n  weathre:\n    enabled: false\n    config: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"plugin", "enable", "weathre", "-dir", dir})
	if err == nil {
		t.Fatal("unknown configured plugin should be rejected")
	}
	if !strings.Contains(err.Error(), "未知插件 \"weathre\"") {
		t.Fatalf("err = %v", err)
	}
	if updated := readTestFile(t, config); strings.Contains(updated, "enabled: true") {
		t.Fatalf("unknown plugin should not be enabled:\n%s", updated)
	}
}

func TestRunPluginDisableAllowsUnknownConfiguredTarget(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins:\n  legacy:\n    enabled: true\n    config: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "disable", "legacy", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已禁用：legacy") {
		t.Fatalf("disable output:\n%s", out.String())
	}
	if updated := readTestFile(t, config); !strings.Contains(updated, "enabled: false") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunPluginEnableAllowsWorkspacePlugin(t *testing.T) {
	dir := t.TempDir()
	config := filepath.Join(dir, "anybot.yaml")
	if err := os.WriteFile(config, []byte("plugins: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := host.AddPluginModule(host.AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "enable", "weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "插件已启用：weather") ||
		!strings.Contains(out.String(), "默认配置待构建同步：weather") {
		t.Fatalf("enable output:\n%s", out.String())
	}
	if updated := readTestFile(t, config); !strings.Contains(updated, "weather:") || !strings.Contains(updated, "enabled: true") {
		t.Fatalf("config:\n%s", updated)
	}
}

func TestRunDoctorHintsExternalWorkspacePlugin(t *testing.T) {
	setTestModuleVersionResolver(t, func(module, query string) (string, error) {
		if module != "github.com/acme/weather" || query != "latest" {
			t.Fatalf("resolve %s@%s", module, query)
		}
		return "v1.2.3", nil
	})
	dir := t.TempDir()
	_, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"plugin", "add", "github.com/acme/weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	if err := run([]string{"plugin", "enable", "weather", "-dir", dir}); err != nil {
		t.Fatal(err)
	}
	err := run([]string{"doctor", "-config", filepath.Join(dir, "anybot.yaml")})
	if err == nil {
		t.Fatal("doctor should reject external plugin in base binary")
	}
	if !strings.Contains(err.Error(), "weather 是工作区外部插件") || !strings.Contains(err.Error(), "anybot up") {
		t.Fatalf("err = %v", err)
	}
}

func TestRunBuildInvokesGoTool(t *testing.T) {
	setTestFrameworkDependencies(t, releaseFrameworkDependencies("v9.9.9"))
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"build", "-dir", dir, "-o", "bot"}); err != nil {
		t.Fatal(err)
	}
	want := append(frameworkGoModCalls(dir, releaseFrameworkDependencies("v9.9.9")),
		dir+" go mod tidy",
		dir+" go build -o bot .",
	)
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "构建完成："+filepath.Join(dir, "bot")) {
		t.Fatalf("build output:\n%s", out.String())
	}
	if _, err := os.Stat(filepath.Join(dir, host.PluginWorkspaceFile)); err != nil {
		t.Fatal(err)
	}
}

func TestRunBuildSyncsWorkspaceGoMod(t *testing.T) {
	setTestFrameworkDependencies(t, releaseFrameworkDependencies("v9.9.9"))
	dir := t.TempDir()
	if _, err := host.AddPluginModule(host.AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather",
		Version: "v1.2.3",
		Replace: "../weather",
	}); err != nil {
		t.Fatal(err)
	}
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	if err := run([]string{"build", "-dir", dir, "-o", "bot"}); err != nil {
		t.Fatal(err)
	}
	want := append(frameworkGoModCalls(dir, releaseFrameworkDependencies("v9.9.9")),
		dir+" go mod edit -require=github.com/acme/weather@v1.2.3",
		dir+" go mod edit -replace=github.com/acme/weather=../weather",
		dir+" go mod tidy",
		dir+" go build -o bot .",
	)
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
}

func TestRunBuildReportsAbsoluteOutput(t *testing.T) {
	setTestFrameworkDependencies(t, releaseFrameworkDependencies("v9.9.9"))
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	commandRunner = func(dir, name string, args ...string) error {
		return nil
	}
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	output := filepath.Join(t.TempDir(), "bot")
	if err := run([]string{"build", "-dir", dir, "-o", output}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "构建完成："+output) {
		t.Fatalf("build output:\n%s", out.String())
	}
}

func TestRunBuildSyncsLocalFrameworkReplace(t *testing.T) {
	deps := []moduleDependency{
		{Module: "github.com/tty00a381/anybot", Version: "v0.0.0", Replace: "../anybot"},
	}
	setTestFrameworkDependencies(t, deps)
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	dir := t.TempDir()
	if err := run([]string{"build", "-dir", dir, "-o", "bot", "-skip-tidy"}); err != nil {
		t.Fatal(err)
	}
	want := append(frameworkGoModCalls(dir, deps),
		dir+" go build -o bot .",
	)
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
}

func TestDetectFrameworkDependencyFindsSourceRoot(t *testing.T) {
	dep := detectFrameworkDependency("github.com/tty00a381/anybot")
	if dep.Module != "github.com/tty00a381/anybot" || dep.Version != "v0.0.0" {
		t.Fatalf("dependency = %#v", dep)
	}
	if dep.Replace == "" {
		t.Fatalf("expected local replace, got %#v", dep)
	}
	if _, err := os.Stat(filepath.Join(dep.Replace, "go.mod")); err != nil {
		t.Fatalf("replace root %q: %v", dep.Replace, err)
	}
}

func TestBinaryPathHelpers(t *testing.T) {
	absOutput := filepath.Join(string(filepath.Separator), "tmp", "bot")
	tests := []struct {
		name    string
		dir     string
		output  string
		built   string
		command string
	}{
		{
			name:    "default output in current directory",
			dir:     ".",
			output:  "",
			built:   "." + string(filepath.Separator) + "anybot-bot",
			command: "." + string(filepath.Separator) + "anybot-bot",
		},
		{
			name:    "relative workspace output",
			dir:     "bot",
			output:  "anybot-bot",
			built:   filepath.Join("bot", "anybot-bot"),
			command: "." + string(filepath.Separator) + "anybot-bot",
		},
		{
			name:    "relative output with directory",
			dir:     ".",
			output:  filepath.Join("bin", "bot"),
			built:   filepath.Join("bin", "bot"),
			command: filepath.Join("bin", "bot"),
		},
		{
			name:    "absolute output",
			dir:     "/workspace",
			output:  absOutput,
			built:   absOutput,
			command: absOutput,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := builtBinaryPath(tt.dir, tt.output); got != tt.built {
				t.Fatalf("builtBinaryPath() = %q, want %q", got, tt.built)
			}
			if got := commandBinaryPath(tt.output); got != tt.command {
				t.Fatalf("commandBinaryPath() = %q, want %q", got, tt.command)
			}
		})
	}
}

func TestRunUpBuildsSyncsAndRuns(t *testing.T) {
	setTestFrameworkDependencies(t, releaseFrameworkDependencies("v9.9.9"))
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	dir := t.TempDir()
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"up", "-dir", dir, "-o", "bot"}); err != nil {
		t.Fatal(err)
	}
	binary := filepath.Join(dir, "bot")
	command := "." + string(filepath.Separator) + "bot"
	want := append(frameworkGoModCalls(dir, releaseFrameworkDependencies("v9.9.9")),
		dir+" go mod tidy",
		dir+" go build -o bot .",
		dir+" "+command+" plugin sync",
		dir+" "+command+" plugin check",
		dir+" "+command+" ",
	)
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "启动："+binary) {
		t.Fatalf("up output:\n%s", out.String())
	}
}

func TestRunUpUsesLocalBinaryForDefaultOutput(t *testing.T) {
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	out, _, restore := captureOutput(t)
	defer restore()
	if err := run([]string{"up", "-skip-build"}); err != nil {
		t.Fatal(err)
	}
	binary := "." + string(filepath.Separator) + "anybot-bot"
	want := []string{
		". " + binary + " plugin sync",
		". " + binary + " plugin check",
		". " + binary + " ",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
	if !strings.Contains(out.String(), "启动："+binary) {
		t.Fatalf("up output:\n%s", out.String())
	}
}

func TestRunUpCanSkipPluginCheck(t *testing.T) {
	oldRunner := commandRunner
	defer func() { commandRunner = oldRunner }()
	var calls []string
	commandRunner = func(dir, name string, args ...string) error {
		calls = append(calls, dir+" "+name+" "+strings.Join(args, " "))
		return nil
	}
	if err := run([]string{"up", "-skip-build", "-skip-check"}); err != nil {
		t.Fatal(err)
	}
	binary := "." + string(filepath.Separator) + "anybot-bot"
	want := []string{
		". " + binary + " plugin sync",
		". " + binary + " ",
	}
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v", calls)
	}
}

func captureOutput(t *testing.T) (*bytes.Buffer, *bytes.Buffer, func()) {
	t.Helper()
	oldStdout := stdout
	oldStderr := stderr
	var out bytes.Buffer
	var errOut bytes.Buffer
	stdout = &out
	stderr = &errOut
	return &out, &errOut, func() {
		stdout = oldStdout
		stderr = oldStderr
	}
}

func setTestFrameworkDependencies(t *testing.T, deps []moduleDependency) {
	t.Helper()
	old := frameworkDependencies
	frameworkDependencies = func() []moduleDependency {
		return append([]moduleDependency(nil), deps...)
	}
	t.Cleanup(func() {
		frameworkDependencies = old
	})
}

func setTestModuleVersionResolver(t *testing.T, resolver func(module, query string) (string, error)) {
	t.Helper()
	old := moduleVersionResolver
	moduleVersionResolver = resolver
	t.Cleanup(func() {
		moduleVersionResolver = old
	})
}

func releaseFrameworkDependencies(version string) []moduleDependency {
	return []moduleDependency{
		{Module: "github.com/tty00a381/anybot", Version: version},
	}
}

func frameworkGoModCalls(dir string, deps []moduleDependency) []string {
	var calls []string
	for _, dep := range deps {
		version := dep.Version
		if version == "" {
			version = "v0.0.0"
		}
		calls = append(calls, dir+" go mod edit -require="+dep.Module+"@"+version)
		if dep.Replace != "" {
			calls = append(calls, dir+" go mod edit -replace="+dep.Module+"="+dep.Replace)
		} else {
			calls = append(calls, dir+" go mod edit -dropreplace="+dep.Module)
		}
	}
	return calls
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
