package host

import (
	"crypto/rand"
	"encoding/base32"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	absdk "github.com/tty00a381/anybot/sdk"
	modmodule "golang.org/x/mod/module"
)

const (
	// PluginLockFile 是 AnyBot 插件安装锁文件。
	PluginLockFile          = "anybot.lock"
	defaultPluginHostModule = "anybot.local/bot"
	generatedPlugins        = "plugins.gen.go"
	generatedMain           = "main.go"
	generatedHeader         = "// Code generated by anybot; DO NOT EDIT."
)

// PluginLock 描述 anybot.lock 中锁定的插件记录。
type PluginLock struct {
	Module  string          `yaml:"module"`
	Plugins []PluginInstall `yaml:"plugins"`
}

// PluginInstall 描述一个插件记录及其来源。ID 是该插件的唯一 PluginID。
type PluginInstall struct {
	ID      string `yaml:"id"`
	Builtin string `yaml:"builtin,omitempty"`
	Module  string `yaml:"module,omitempty"`
	Version string `yaml:"version,omitempty"`
	Replace string `yaml:"replace,omitempty"`
}

// AddPluginInstallOptions 描述 anybot plugin add 的插件锁更新参数。
type AddPluginInstallOptions struct {
	Dir     string
	ID      string
	Builtin string
	Module  string
	Version string
	Replace string
}

// UpdatePluginInstallOptions 描述 anybot plugin update 的插件锁更新参数。
type UpdatePluginInstallOptions struct {
	Dir          string
	ID           string
	Version      string
	Replace      string
	SetVersion   bool
	SetReplace   bool
	ClearReplace bool
}

// RemovePluginInstallOptions 描述 anybot plugin remove 的插件锁更新参数。
type RemovePluginInstallOptions struct {
	Dir string
	ID  string
}

// UnknownBuiltinError 表示插件锁引用了当前框架不存在的内置插件来源。
type UnknownBuiltinError struct {
	Source string
}

func (err UnknownBuiltinError) Error() string {
	return fmt.Sprintf("unknown builtin plugin %q", err.Source)
}

// NewUnknownBuiltinError 创建未知内置插件来源错误。
func NewUnknownBuiltinError(source string) error {
	return UnknownBuiltinError{Source: source}
}

// EnsurePluginHost 确保目录中存在可构建的插件宿主。
func EnsurePluginHost(dir string) (PluginLock, error) {
	return EnsurePluginHostForce(dir, false)
}

// EnsurePluginHostForce 确保插件宿主存在；force 允许接管同名非生成文件。
func EnsurePluginHostForce(dir string, force bool) (PluginLock, error) {
	if dir == "" {
		dir = "."
	}
	lockPath := filepath.Join(dir, PluginLockFile)
	missing := false
	if _, err := os.Stat(lockPath); errors.Is(err, os.ErrNotExist) {
		missing = true
	} else if err != nil {
		return PluginLock{}, err
	}
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(dir, force); err != nil {
		return PluginLock{}, err
	}
	if missing {
		if err := SavePluginLock(lockPath, lock); err != nil {
			return PluginLock{}, err
		}
	}
	if err := renderPluginHost(dir, lock, force); err != nil {
		return PluginLock{}, err
	}
	return lock, nil
}

// NewDefaultPluginLock 创建包含首发内置插件记录的新插件锁。
func NewDefaultPluginLock() (PluginLock, error) {
	lock := defaultPluginLock()
	for _, builtin := range BuiltinPlugins() {
		id, err := NewPluginID()
		if err != nil {
			return PluginLock{}, err
		}
		lock.Plugins = append(lock.Plugins, PluginInstall{
			ID:      id,
			Builtin: builtin.Source,
		})
	}
	return lock, nil
}

// AddPluginInstall 把插件记录写入插件锁并重写生成宿主。
func AddPluginInstall(opts AddPluginInstallOptions) (PluginLock, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	opts.Builtin = strings.TrimSpace(opts.Builtin)
	opts.Module = strings.TrimSpace(opts.Module)
	if (opts.Builtin == "") == (opts.Module == "") {
		return PluginLock{}, fmt.Errorf("plugin source is required")
	}
	if opts.Builtin != "" {
		if opts.Version != "" || opts.Replace != "" {
			return PluginLock{}, fmt.Errorf("builtin plugin cannot use version or replace")
		}
		if _, ok := BuiltinFactory(opts.Builtin); !ok {
			return PluginLock{}, NewUnknownBuiltinError(opts.Builtin)
		}
	} else {
		module, version, err := ParsePluginModuleSpec(opts.Module)
		if err != nil {
			return PluginLock{}, err
		}
		if opts.Version != "" && version != "" && opts.Version != version {
			return PluginLock{}, fmt.Errorf("plugin version conflict: %s and %s", version, opts.Version)
		}
		if opts.Version == "" {
			opts.Version = version
		}
		opts.Module = module
	}
	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginLock{}, err
	}
	if opts.ID == "" {
		opts.ID, err = NewPluginID()
		if err != nil {
			return PluginLock{}, err
		}
	}
	item := PluginInstall{
		ID:      opts.ID,
		Builtin: opts.Builtin,
		Module:  opts.Module,
		Version: opts.Version,
		Replace: strings.TrimSpace(opts.Replace),
	}
	if err := lock.add(item); err != nil {
		return PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginLock{}, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginLock{}, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginLock{}, err
	}
	return lock, nil
}

// UpdatePluginInstall 就地更新外部插件元数据并重写生成文件。
func UpdatePluginInstall(opts UpdatePluginInstallOptions) (PluginInstall, PluginLock, bool, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.ID == "" {
		return PluginInstall{}, PluginLock{}, false, fmt.Errorf("plugin id is required")
	}
	if opts.SetReplace && opts.ClearReplace {
		return PluginInstall{}, PluginLock{}, false, fmt.Errorf("-replace and -clear-replace cannot be used together")
	}

	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginInstall{}, PluginLock{}, false, err
	}
	index := -1
	for i, item := range lock.Plugins {
		if item.ID == opts.ID {
			index = i
			break
		}
	}
	if index < 0 {
		return PluginInstall{}, PluginLock{}, false, fmt.Errorf("plugin %s not found", opts.ID)
	}

	original := lock.Plugins[index]
	if original.Builtin != "" {
		return PluginInstall{}, PluginLock{}, false, fmt.Errorf("builtin plugin %s cannot be updated as a Go module", opts.ID)
	}
	updated := original
	if opts.SetVersion {
		updated.Version = strings.TrimSpace(opts.Version)
	}
	if opts.SetReplace {
		updated.Replace = strings.TrimSpace(opts.Replace)
	}
	if opts.ClearReplace {
		updated.Replace = ""
	}
	lock.Plugins[index] = updated
	lock.applyDefaults()
	updated = lock.Plugins[index]
	changed := original != updated
	if !changed {
		return updated, lock, false, nil
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginInstall{}, PluginLock{}, false, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginInstall{}, PluginLock{}, false, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginInstall{}, PluginLock{}, false, err
	}
	return updated, lock, true, nil
}

// RemovePluginInstall 从插件锁移除插件记录并重写生成宿主。
func RemovePluginInstall(opts RemovePluginInstallOptions) (PluginInstall, PluginLock, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.ID == "" {
		return PluginInstall{}, PluginLock{}, fmt.Errorf("plugin id is required")
	}
	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginInstall{}, PluginLock{}, err
	}
	removed, err := lock.remove(opts.ID)
	if err != nil {
		return PluginInstall{}, PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginInstall{}, PluginLock{}, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginInstall{}, PluginLock{}, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginInstall{}, PluginLock{}, err
	}
	return removed, lock, nil
}

func (lock *PluginLock) add(item PluginInstall) error {
	lock.applyDefaults()
	if err := ValidatePluginInstall(item); err != nil {
		return err
	}
	for _, existing := range lock.Plugins {
		if existing.ID == item.ID {
			return fmt.Errorf("plugin id %s already exists", item.ID)
		}
		if item.Module != "" && existing.Module == item.Module {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
		if item.Builtin != "" && existing.Builtin == item.Builtin {
			return fmt.Errorf("builtin plugin %s already exists", item.Builtin)
		}
	}
	lock.Plugins = append(lock.Plugins, item)
	sort.Slice(lock.Plugins, func(i, j int) bool {
		return lock.Plugins[i].ID < lock.Plugins[j].ID
	})
	return nil
}

func (lock *PluginLock) remove(id string) (PluginInstall, error) {
	lock.applyDefaults()
	for i, existing := range lock.Plugins {
		if existing.ID == id {
			lock.Plugins = append(lock.Plugins[:i], lock.Plugins[i+1:]...)
			return existing, nil
		}
	}
	return PluginInstall{}, fmt.Errorf("plugin %s not found", id)
}

func (lock *PluginLock) applyDefaults() {
	if lock.Module == "" {
		lock.Module = defaultPluginHostModule
	}
	for i := range lock.Plugins {
		lock.Plugins[i].Builtin = strings.TrimSpace(lock.Plugins[i].Builtin)
		lock.Plugins[i].Module = strings.TrimSpace(lock.Plugins[i].Module)
		if lock.Plugins[i].Module != "" {
			if module, version, err := ParsePluginModuleSpec(lock.Plugins[i].Module); err == nil {
				lock.Plugins[i].Module = module
				if lock.Plugins[i].Version == "" {
					lock.Plugins[i].Version = version
				}
			}
		}
		lock.Plugins[i].Replace = strings.TrimSpace(lock.Plugins[i].Replace)
	}
}

func defaultPluginLock() PluginLock {
	return PluginLock{Module: defaultPluginHostModule}
}

// ValidatePluginLock 校验插件安装锁是否可生成稳定 Go 代码。
func ValidatePluginLock(lock PluginLock) error {
	lock.applyDefaults()
	seenIDs := map[string]struct{}{}
	seenModules := map[string]struct{}{}
	seenBuiltins := map[string]struct{}{}
	for _, item := range lock.Plugins {
		if err := ValidatePluginInstall(item); err != nil {
			return err
		}
		if _, exists := seenIDs[item.ID]; exists {
			return fmt.Errorf("plugin id %s already exists", item.ID)
		}
		seenIDs[item.ID] = struct{}{}
		if item.Module != "" {
			if _, exists := seenModules[item.Module]; exists {
				return fmt.Errorf("plugin module %s already exists", item.Module)
			}
			seenModules[item.Module] = struct{}{}
		}
		if item.Builtin != "" {
			if _, exists := seenBuiltins[item.Builtin]; exists {
				return fmt.Errorf("builtin plugin %s already exists", item.Builtin)
			}
			seenBuiltins[item.Builtin] = struct{}{}
		}
	}
	return nil
}

// ValidatePluginInstall 校验单个插件记录。
func ValidatePluginInstall(item PluginInstall) error {
	if item.ID == "" {
		return fmt.Errorf("plugin id is required")
	}
	if err := ValidatePluginID(item.ID); err != nil {
		return fmt.Errorf("plugin id %q is invalid: %w", item.ID, err)
	}
	if !strings.HasPrefix(item.ID, "plg_") {
		return fmt.Errorf("plugin id %q is invalid: installed PluginID must be generated by anybot", item.ID)
	}
	if (item.Builtin == "") == (item.Module == "") {
		return fmt.Errorf("plugin source is required")
	}
	if item.Builtin != "" {
		if _, ok := BuiltinFactory(item.Builtin); !ok {
			return NewUnknownBuiltinError(item.Builtin)
		}
		if item.Version != "" || item.Replace != "" {
			return fmt.Errorf("builtin plugin %s cannot use version or replace", item.Builtin)
		}
		return nil
	}
	if err := modmodule.CheckPath(item.Module); err != nil {
		return fmt.Errorf("plugin module %q is invalid: %w", item.Module, err)
	}
	if item.Version != "" {
		if err := modmodule.Check(item.Module, item.Version); err != nil {
			return fmt.Errorf("plugin version %q is invalid for %s: %w", item.Version, item.Module, err)
		}
	}
	return nil
}

// ValidatePluginInstallSource 校验单个插件记录。
func ValidatePluginInstallSource(item PluginInstall) error {
	return ValidatePluginInstall(item)
}

// ValidatePluginID 校验插件 ID 能安全用于锁文件、配置文件、状态前缀和数据目录。
func ValidatePluginID(id string) error {
	return absdk.ValidatePluginID(id)
}

// ParsePluginModuleSpec 解析 module 或 module@version 形式的插件来源。
func ParsePluginModuleSpec(spec string) (module string, version string, err error) {
	spec = strings.TrimSpace(spec)
	if spec == "" {
		return "", "", fmt.Errorf("plugin module is required")
	}
	at := strings.LastIndex(spec, "@")
	if at < 0 {
		return spec, "", nil
	}
	module = strings.TrimSpace(spec[:at])
	version = strings.TrimSpace(spec[at+1:])
	if module == "" || version == "" {
		return "", "", fmt.Errorf("plugin module %q must be module@version", spec)
	}
	return module, version, nil
}

// NewPluginID 生成一个新的本地 PluginID。
func NewPluginID() (string, error) {
	var data [16]byte
	if _, err := rand.Read(data[:]); err != nil {
		return "", err
	}
	encoded := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(data[:])
	return "plg_" + strings.ToLower(encoded), nil
}
