package host

import (
	"crypto/rand"
	"encoding/base32"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	absdk "github.com/tty00a381/anybot/sdk"
	modmodule "golang.org/x/mod/module"
)

const (
	// PluginLockFile 是 AnyBot 外部插件锁文件。
	PluginLockFile   = "anybot.lock"
	generatedPlugins = "plugins.gen.go"
	generatedMain    = "main.go"
	generatedHeader  = "// Code generated by anybot; DO NOT EDIT."
)

// PluginLock 描述 anybot.lock 中锁定的外部插件来源。
type PluginLock struct {
	Module  string         `yaml:"module"`
	Plugins []PluginModule `yaml:"plugins"`
}

// PluginModule 描述一个外部插件安装实例及其来源。
type PluginModule struct {
	ID      string `yaml:"id"`
	Module  string `yaml:"module"`
	Version string `yaml:"version,omitempty"`
	Replace string `yaml:"replace,omitempty"`
}

// AddPluginOptions 描述 anybot plugin add 的插件锁更新参数。
type AddPluginOptions struct {
	Dir     string
	ID      string
	Module  string
	Version string
	Replace string
}

// UpdatePluginOptions 描述 anybot plugin update 的插件锁更新参数。
type UpdatePluginOptions struct {
	Dir          string
	ID           string
	Version      string
	Replace      string
	SetVersion   bool
	SetReplace   bool
	ClearReplace bool
}

// RemovePluginOptions 描述 anybot plugin remove 的插件锁更新参数。
type RemovePluginOptions struct {
	Dir string
	ID  string
}

// EnsurePluginHost 确保目录中存在可构建的插件宿主。
func EnsurePluginHost(dir string) (PluginLock, error) {
	return EnsurePluginHostForce(dir, false)
}

// EnsurePluginHostForce 确保插件宿主存在；force 允许接管同名非生成文件。
func EnsurePluginHostForce(dir string, force bool) (PluginLock, error) {
	if dir == "" {
		dir = "."
	}
	lockPath := filepath.Join(dir, PluginLockFile)
	missing := false
	if _, err := os.Stat(lockPath); errors.Is(err, os.ErrNotExist) {
		missing = true
	} else if err != nil {
		return PluginLock{}, err
	}
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(dir, force); err != nil {
		return PluginLock{}, err
	}
	if missing {
		if err := SavePluginLock(lockPath, lock); err != nil {
			return PluginLock{}, err
		}
	}
	if err := renderPluginHost(dir, lock, force); err != nil {
		return PluginLock{}, err
	}
	return lock, nil
}

// AddPluginModule 把外部插件写入插件锁并重写生成宿主。
func AddPluginModule(opts AddPluginOptions) (PluginLock, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Module == "" {
		return PluginLock{}, fmt.Errorf("plugin module is required")
	}
	module, version, err := ParsePluginModuleSpec(opts.Module)
	if err != nil {
		return PluginLock{}, err
	}
	if opts.Version != "" && version != "" && opts.Version != version {
		return PluginLock{}, fmt.Errorf("plugin version conflict: %s and %s", version, opts.Version)
	}
	if opts.Version == "" {
		opts.Version = version
	}
	opts.Module = module
	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginLock{}, err
	}
	if opts.ID == "" {
		opts.ID, err = NewPluginID()
		if err != nil {
			return PluginLock{}, err
		}
	}
	item := PluginModule{
		ID:      opts.ID,
		Module:  opts.Module,
		Version: opts.Version,
		Replace: strings.TrimSpace(opts.Replace),
	}
	if err := lock.add(item); err != nil {
		return PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginLock{}, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginLock{}, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginLock{}, err
	}
	return lock, nil
}

// UpdatePluginModule 就地更新外部插件元数据并重写生成文件。
func UpdatePluginModule(opts UpdatePluginOptions) (PluginModule, PluginLock, bool, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.ID == "" {
		return PluginModule{}, PluginLock{}, false, fmt.Errorf("plugin id is required")
	}
	if opts.SetReplace && opts.ClearReplace {
		return PluginModule{}, PluginLock{}, false, fmt.Errorf("-replace and -clear-replace cannot be used together")
	}

	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	index := -1
	for i, item := range lock.Plugins {
		if item.ID == opts.ID {
			index = i
			break
		}
	}
	if index < 0 {
		return PluginModule{}, PluginLock{}, false, fmt.Errorf("plugin %s not found", opts.ID)
	}

	original := lock.Plugins[index]
	updated := original
	if opts.SetVersion {
		updated.Version = strings.TrimSpace(opts.Version)
	}
	if opts.SetReplace {
		updated.Replace = strings.TrimSpace(opts.Replace)
	}
	if opts.ClearReplace {
		updated.Replace = ""
	}
	lock.Plugins[index] = updated
	lock.applyDefaults()
	updated = lock.Plugins[index]
	changed := original != updated
	if !changed {
		return updated, lock, false, nil
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	return updated, lock, true, nil
}

// RemovePluginModule 从插件锁移除外部插件并重写生成宿主。
func RemovePluginModule(opts RemovePluginOptions) (PluginModule, PluginLock, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.ID == "" {
		return PluginModule{}, PluginLock{}, fmt.Errorf("plugin id is required")
	}
	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	removed, err := lock.remove(opts.ID)
	if err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	return removed, lock, nil
}

func (lock *PluginLock) add(item PluginModule) error {
	lock.applyDefaults()
	if err := ValidatePluginModule(item); err != nil {
		return err
	}
	for _, existing := range lock.Plugins {
		if existing.ID == item.ID {
			return fmt.Errorf("plugin id %s already exists", item.ID)
		}
		if existing.Module == item.Module {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
	}
	lock.Plugins = append(lock.Plugins, item)
	sort.Slice(lock.Plugins, func(i, j int) bool {
		return lock.Plugins[i].ID < lock.Plugins[j].ID
	})
	return nil
}

func (lock *PluginLock) remove(id string) (PluginModule, error) {
	lock.applyDefaults()
	for i, existing := range lock.Plugins {
		if existing.ID == id {
			lock.Plugins = append(lock.Plugins[:i], lock.Plugins[i+1:]...)
			return existing, nil
		}
	}
	return PluginModule{}, fmt.Errorf("plugin %s not found", id)
}

func (lock *PluginLock) applyDefaults() {
	if lock.Module == "" {
		lock.Module = "anybot.local/bot"
	}
	for i := range lock.Plugins {
		if module, version, err := ParsePluginModuleSpec(lock.Plugins[i].Module); err == nil {
			lock.Plugins[i].Module = module
			if lock.Plugins[i].Version == "" {
				lock.Plugins[i].Version = version
			}
		}
		lock.Plugins[i].Replace = strings.TrimSpace(lock.Plugins[i].Replace)
	}
}

func defaultPluginLock() PluginLock {
	return PluginLock{Module: "anybot.local/bot"}
}

// ValidatePluginLock 校验外部插件锁是否可生成稳定 Go 代码。
func ValidatePluginLock(lock PluginLock) error {
	lock.applyDefaults()
	seenIDs := map[string]struct{}{}
	seenModules := map[string]struct{}{}
	for _, item := range lock.Plugins {
		if err := ValidatePluginModule(item); err != nil {
			return err
		}
		if _, exists := seenIDs[item.ID]; exists {
			return fmt.Errorf("plugin id %s already exists", item.ID)
		}
		seenIDs[item.ID] = struct{}{}
		if _, exists := seenModules[item.Module]; exists {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
		seenModules[item.Module] = struct{}{}
	}
	return nil
}

// ValidatePluginModule 校验单个外部插件模块元数据。
func ValidatePluginModule(item PluginModule) error {
	if item.ID == "" {
		return fmt.Errorf("plugin id is required")
	}
	if err := ValidatePluginID(item.ID); err != nil {
		return fmt.Errorf("plugin id %q is invalid: %w", item.ID, err)
	}
	if item.Module == "" {
		return fmt.Errorf("plugin module is required")
	}
	if err := modmodule.CheckPath(item.Module); err != nil {
		return fmt.Errorf("plugin module %q is invalid: %w", item.Module, err)
	}
	if item.Version != "" {
		if err := modmodule.Check(item.Module, item.Version); err != nil {
			return fmt.Errorf("plugin version %q is invalid for %s: %w", item.Version, item.Module, err)
		}
	}
	return nil
}

// ValidatePluginID 校验插件 ID 能安全用于锁文件、配置文件、状态前缀和数据目录。
func ValidatePluginID(id string) error {
	return absdk.ValidatePluginID(id)
}

// ParsePluginModuleSpec 解析 module 或 module@version 形式的插件来源。
func ParsePluginModuleSpec(spec string) (module string, version string, err error) {
	spec = strings.TrimSpace(spec)
	if spec == "" {
		return "", "", fmt.Errorf("plugin module is required")
	}
	at := strings.LastIndex(spec, "@")
	if at < 0 {
		return spec, "", nil
	}
	module = strings.TrimSpace(spec[:at])
	version = strings.TrimSpace(spec[at+1:])
	if module == "" || version == "" {
		return "", "", fmt.Errorf("plugin module %q must be module@version", spec)
	}
	return module, version, nil
}

// NewPluginID 生成一个新的本地插件安装 ID。
func NewPluginID() (string, error) {
	var data [16]byte
	if _, err := rand.Read(data[:]); err != nil {
		return "", err
	}
	encoded := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(data[:])
	return "plg_" + strings.ToLower(encoded), nil
}
