package host

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// RenderPluginHost 重写生成宿主插件注册代码，并在缺失时创建最小生成宿主。
func RenderPluginHost(dir string, lock PluginLock) error {
	return renderPluginHost(dir, lock, false)
}

func renderPluginHost(dir string, lock PluginLock, force bool) error {
	if dir == "" {
		dir = "."
	}
	lock.applyDefaults()
	if err := ValidatePluginLock(lock); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := CheckGeneratedHostWritable(dir, force); err != nil {
		return err
	}
	if err := writeGenerated(filepath.Join(dir, generatedPlugins), renderPlugins(lock), force); err != nil {
		return err
	}
	if err := writeGenerated(filepath.Join(dir, generatedMain), renderMain(), force); err != nil {
		return err
	}
	if force {
		return writeGeneratedGoMod(filepath.Join(dir, "go.mod"), renderGoMod(lock))
	}
	return writeGeneratedGoModIfMissing(filepath.Join(dir, "go.mod"), renderGoMod(lock))
}

func renderPlugins(lock PluginLock) string {
	type pluginImport struct {
		Alias  string
		ID     string
		Module string
	}
	data := struct {
		Plugins []pluginImport
	}{}
	for _, item := range lock.Plugins {
		if item.Module == "" {
			continue
		}
		i := len(data.Plugins)
		data.Plugins = append(data.Plugins, pluginImport{
			Alias:  fmt.Sprintf("plugin%d", i),
			ID:     item.ID,
			Module: item.Module,
		})
	}
	return mustFormat(executeTemplate(pluginsTemplate, data))
}

func renderMain() string {
	return mustFormat(executeTemplate(mainTemplate, nil))
}

func renderGoMod(lock PluginLock) string {
	lock.applyDefaults()
	return generatedHeader + "\n\nmodule " + lock.Module + "\n\ngo 1.24\n"
}

func executeTemplate(src string, data any) string {
	tpl := template.Must(template.New("lock").Parse(src))
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		panic(err)
	}
	return buf.String()
}

func mustFormat(src string) string {
	out, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(out)
}

const pluginsTemplate = `// Code generated by anybot; DO NOT EDIT.

package main

import (
	absdk "github.com/tty00a381/anybot/sdk"
	{{- range .Plugins }}
	{{ .Alias }} "{{ .Module }}"
	{{- end }}
)

func registerGeneratedPlugins(registry absdk.Registry) error {
	{{- range .Plugins }}
	if err := registry.Register({{ .Alias }}.Plugin.Factory().WithPluginID({{ printf "%q" .ID }})); err != nil {
		return err
	}
	{{- end }}
	return nil
}
`

const mainTemplate = `// Code generated by anybot; DO NOT EDIT.

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/tty00a381/anybot/app/host"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	external := host.EmptyRegistry()
	if err := registerGeneratedPlugins(external); err != nil {
		log.Fatal(err)
	}
	if len(os.Args) > 1 && os.Args[1] == "plugin" {
		if err := host.RunPluginCommand(host.PluginCommandOptions{
			Args:       os.Args[2:],
			Output:     os.Stdout,
			ConfigPath: "anybot.yaml",
			LockPath:   host.PluginLockFile,
			Registry:   external,
		}); err != nil {
			log.Fatal(err)
		}
		return
	}

	cfg, err := host.LoadConfig("anybot.yaml")
	if err != nil {
		log.Fatal(err)
	}
	logger, err := host.NewLogger(cfg.Runtime.LogLevel, os.Stderr)
	if err != nil {
		log.Fatal(err)
	}
	lock, err := host.LoadPluginLock(host.PluginLockFile)
	if err != nil {
		log.Fatal(err)
	}
	app, err := host.NewApp(cfg, external, logger, host.WithConfigPath("anybot.yaml"), host.WithRuntimeState(), host.WithPluginLock(lock))
	if err != nil {
		log.Fatal(err)
	}
	if err := app.Run(ctx); err != nil && ctx.Err() == nil {
		log.Fatal(err)
	}
}
`
