package host

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tty00a381/anybot/internal/scaffold"
)

func TestAddPluginModuleGeneratesLockAndHost(t *testing.T) {
	dir := t.TempDir()
	lock, err := AddPluginModule(AddPluginOptions{
		Dir:    dir,
		Module: "github.com/acme/anybot-weather",
		Symbol: "Weather",
	})
	if err != nil {
		t.Fatal(err)
	}
	if lock.Module != "anybot.local/bot" || len(lock.Plugins) != 1 {
		t.Fatalf("lock = %#v", lock)
	}
	if lock.Plugins[0].Name != "anybot_weather" {
		t.Fatalf("plugin name = %q", lock.Plugins[0].Name)
	}
	wantID := DefaultPluginInstanceID("github.com/acme/anybot-weather", "Weather")
	if lock.Plugins[0].ID != wantID {
		t.Fatalf("plugin id = %q, want %q", lock.Plugins[0].ID, wantID)
	}
	lockText := readFile(t, filepath.Join(dir, PluginLockFile))
	if !strings.Contains(lockText, "github.com/acme/anybot-weather") || !strings.Contains(lockText, "id: "+wantID) {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if !strings.Contains(generated, "Code generated by anybot") ||
		!strings.Contains(generated, `plugin0 "github.com/acme/anybot-weather"`) ||
		!strings.Contains(generated, `plugin0.Weather.Factory().WithName("anybot_weather").WithInstanceID("`+wantID+`")`) {
		t.Fatalf("generated:\n%s", generated)
	}
	mainGo := readFile(t, filepath.Join(dir, generatedMain))
	if !strings.Contains(mainGo, "Code generated by anybot") ||
		!strings.Contains(mainGo, "registerExternalPlugins(registry)") ||
		!strings.Contains(mainGo, `os.Args[1] == "plugin"`) ||
		!strings.Contains(mainGo, "host.RunPluginCommand") ||
		!strings.Contains(mainGo, "Args:       os.Args[2:]") ||
		!strings.Contains(mainGo, "host.NewApp") {
		t.Fatalf("main.go:\n%s", mainGo)
	}
	if strings.Contains(mainGo, "host.SyncPluginConfigEntry") ||
		strings.Contains(mainGo, "host.WritePluginStatusTable") ||
		strings.Contains(mainGo, "host.EnsureKnownPluginTarget") {
		t.Fatalf("generated main should delegate plugin command handling:\n%s", mainGo)
	}
	goMod := readFile(t, filepath.Join(dir, "go.mod"))
	if !strings.Contains(goMod, "module anybot.local/bot") {
		t.Fatalf("go.mod:\n%s", goMod)
	}
}

func TestEnsurePluginHostCreatesEmptyHost(t *testing.T) {
	dir := t.TempDir()
	lock, err := EnsurePluginHost(dir)
	if err != nil {
		t.Fatal(err)
	}
	if lock.Module != "anybot.local/bot" || len(lock.Plugins) != 0 {
		t.Fatalf("lock = %#v", lock)
	}
	lockText := readFile(t, filepath.Join(dir, PluginLockFile))
	if !strings.Contains(lockText, "module: anybot.local/bot") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if !strings.Contains(generated, "Code generated by anybot") ||
		!strings.Contains(generated, "func registerExternalPlugins") {
		t.Fatalf("plugins.gen.go:\n%s", generated)
	}
	mainGo := readFile(t, filepath.Join(dir, generatedMain))
	if !strings.Contains(mainGo, "host.DefaultRegistry()") {
		t.Fatalf("main.go:\n%s", mainGo)
	}
	goMod := readFile(t, filepath.Join(dir, "go.mod"))
	if !strings.Contains(goMod, "module anybot.local/bot") {
		t.Fatalf("go.mod:\n%s", goMod)
	}
}

func TestLoadPluginLockAcceptsCustomPath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "plugin-lock.yaml")
	if err := os.WriteFile(path, []byte("module: anybot.local/bot\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	lock, err := LoadPluginLock(path)
	if err != nil {
		t.Fatal(err)
	}
	if lock.Module != "anybot.local/bot" {
		t.Fatalf("lock = %#v", lock)
	}
}

func TestLoadPluginLockValidatesLock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, PluginLockFile)
	if err := os.WriteFile(path, []byte(`module: anybot.local/bot
plugins:
  - name: weather
    module: github.com/acme/weather
    symbol: Plugin
  - name: weather
    module: github.com/acme/other
    symbol: Plugin
`), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := LoadPluginLock(path)
	if err == nil || !strings.Contains(err.Error(), "plugin weather already exists") {
		t.Fatalf("err = %v", err)
	}
}

func TestAddPluginModuleRejectsInvalidNameBeforeWriting(t *testing.T) {
	dir := t.TempDir()
	_, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "bad/name", Module: "github.com/acme/weather"})
	if err == nil || !strings.Contains(err.Error(), `plugin name "bad/name" is invalid`) {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, PluginLockFile)); !os.IsNotExist(err) {
		t.Fatalf("lock should not be written: %v", err)
	}
}

func TestAddPluginModuleParsesVersionAndReplace(t *testing.T) {
	dir := t.TempDir()
	lock, err := AddPluginModule(AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather@v1.2.3",
		Replace: "../weather",
	})
	if err != nil {
		t.Fatal(err)
	}
	item := lock.Plugins[0]
	if item.Module != "github.com/acme/weather" || item.Version != "v1.2.3" || item.Replace != "../weather" {
		t.Fatalf("plugin = %#v", item)
	}
	lockText := readFile(t, filepath.Join(dir, PluginLockFile))
	if !strings.Contains(lockText, "version: v1.2.3") ||
		!strings.Contains(lockText, "id: "+DefaultPluginInstanceID("github.com/acme/weather", "Plugin")) ||
		!strings.Contains(lockText, "replace: ../weather") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if strings.Contains(generated, "@v1.2.3") || !strings.Contains(generated, `plugin0 "github.com/acme/weather"`) {
		t.Fatalf("generated:\n%s", generated)
	}
}

func TestRenderPluginHostUpdatesGeneratedMain(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, generatedMain), []byte(generatedHeader+"\n\npackage main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	lock, err := LoadPluginLock(filepath.Join(dir, PluginLockFile))
	if err != nil {
		t.Fatal(err)
	}
	if err := RenderPluginHost(dir, lock); err != nil {
		t.Fatal(err)
	}
	mainGo := readFile(t, filepath.Join(dir, generatedMain))
	if !strings.Contains(mainGo, "Code generated by anybot") ||
		!strings.Contains(mainGo, "host.RunPluginCommand") ||
		!strings.Contains(mainGo, "host.NewApp") {
		t.Fatalf("main.go:\n%s", mainGo)
	}
}

func TestRenderPluginHostRejectsUnmanagedMain(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, generatedMain), []byte("package main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := RenderPluginHost(dir, PluginLock{})
	if err == nil {
		t.Fatal("unmanaged main.go should be rejected")
	}
	if !strings.Contains(err.Error(), "不是 anybot 生成文件") {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, generatedPlugins)); !os.IsNotExist(err) {
		t.Fatalf("plugins.gen.go should not be written after preflight failure: %v", err)
	}
}

func TestAddPluginModuleRejectsDuplicates(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "weather2", Module: "github.com/acme/weather"}); err == nil {
		t.Fatal("duplicate module should be rejected")
	}
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather2"}); err == nil {
		t.Fatal("duplicate name should be rejected")
	}
}

func TestAddPluginModuleRejectsUnexportedSymbol(t *testing.T) {
	dir := t.TempDir()
	_, err := AddPluginModule(AddPluginOptions{Dir: dir, Module: "github.com/acme/weather", Symbol: "module"})
	if err == nil {
		t.Fatal("unexported symbol should be rejected")
	}
	if !strings.Contains(err.Error(), "must be an exported Go identifier") {
		t.Fatalf("err = %v", err)
	}
}

func TestUpdatePluginModuleUpdatesMetadata(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginModule(AddPluginOptions{
		Dir:     dir,
		Name:    "weather",
		Module:  "github.com/acme/weather@v1.2.3",
		Replace: "../weather",
		Symbol:  "Module",
	}); err != nil {
		t.Fatal(err)
	}
	updated, lock, changed, err := UpdatePluginModule(UpdatePluginOptions{
		Dir:          dir,
		Name:         "weather",
		Version:      "v1.3.0",
		Symbol:       "Weather",
		SetVersion:   true,
		SetSymbol:    true,
		ClearReplace: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("update should report change")
	}
	wantID := DefaultPluginInstanceID("github.com/acme/weather", "Module")
	if updated.Version != "v1.3.0" || updated.Replace != "" || updated.Symbol != "Weather" || updated.ID != wantID {
		t.Fatalf("updated = %#v", updated)
	}
	if len(lock.Plugins) != 1 || lock.Plugins[0] != updated {
		t.Fatalf("lock = %#v", lock)
	}
	lockText := readFile(t, filepath.Join(dir, PluginLockFile))
	if !strings.Contains(lockText, "version: v1.3.0") ||
		strings.Contains(lockText, "replace:") ||
		!strings.Contains(lockText, "symbol: Weather") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if !strings.Contains(generated, `registry.Register(plugin0.Weather.Factory().WithName("weather").WithInstanceID("`+wantID+`"))`) {
		t.Fatalf("generated:\n%s", generated)
	}
}

func TestUpdatePluginModuleRejectsInvalidInputs(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, _, _, err := UpdatePluginModule(UpdatePluginOptions{Dir: dir, Name: "missing", SetVersion: true, Version: "v1.0.0"}); err == nil {
		t.Fatal("missing plugin should be rejected")
	}
	if _, _, _, err := UpdatePluginModule(UpdatePluginOptions{Dir: dir, Name: "weather", SetSymbol: true, Symbol: "weather"}); err == nil {
		t.Fatal("unexported symbol should be rejected")
	}
	if _, _, _, err := UpdatePluginModule(UpdatePluginOptions{Dir: dir, Name: "weather", SetReplace: true, ClearReplace: true}); err == nil {
		t.Fatal("replace conflict should be rejected")
	}
}

func TestDefaultPluginName(t *testing.T) {
	if got := DefaultPluginName("github.com/acme/anybot-weather.git"); got != "anybot_weather" {
		t.Fatalf("name = %q", got)
	}
	if got := DefaultPluginName("github.com/acme/anybot-weather@v1.2.3"); got != "anybot_weather" {
		t.Fatalf("versioned name = %q", got)
	}
	if got := DefaultPluginName("github.com/acme/anybot-weather/v2"); got != "anybot_weather" {
		t.Fatalf("path-major name = %q", got)
	}
	if got := DefaultPluginName("gopkg.in/acme/weather.v2"); got != "weather" {
		t.Fatalf("gopkg name = %q", got)
	}
	if got := DefaultPluginName("///"); got != "plugin" {
		t.Fatalf("empty name = %q", got)
	}
}

func TestRemovePluginModuleUpdatesLockAndHost(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "weather", Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, err := AddPluginModule(AddPluginOptions{Dir: dir, Name: "memory", Module: "github.com/acme/memory"}); err != nil {
		t.Fatal(err)
	}
	removed, lock, err := RemovePluginModule(RemovePluginOptions{Dir: dir, Name: "weather"})
	if err != nil {
		t.Fatal(err)
	}
	if removed.Module != "github.com/acme/weather" || len(lock.Plugins) != 1 || lock.Plugins[0].Name != "memory" {
		t.Fatalf("removed=%#v lock=%#v", removed, lock)
	}
	lockText := readFile(t, filepath.Join(dir, PluginLockFile))
	if strings.Contains(lockText, "github.com/acme/weather") || !strings.Contains(lockText, "github.com/acme/memory") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if strings.Contains(generated, "github.com/acme/weather") || !strings.Contains(generated, `plugin0 "github.com/acme/memory"`) {
		t.Fatalf("generated:\n%s", generated)
	}
}

func TestRemovePluginModuleRejectsMissing(t *testing.T) {
	dir := t.TempDir()
	if _, _, err := RemovePluginModule(RemovePluginOptions{Dir: dir, Name: "missing"}); err == nil {
		t.Fatal("missing plugin should be rejected")
	}
}

func TestGeneratedPluginLockBuildsLocalPlugin(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	pluginDir := filepath.Join(dir, "weather")
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "go.mod"), []byte(`module example.com/weather

go 1.24

require github.com/tty00a381/anybot v0.0.0
`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "weather.go"), []byte(`package weather

import (
	absdk "github.com/tty00a381/anybot/sdk"
)

type Config struct {
	Command string `+"`yaml:\"command\"`"+`
}

var Plugin = absdk.Define(
	absdk.Manifest{Name: "weather", Version: "1.0.0", Description: "天气插件"},
	Config{Command: "weather"},
	func(ctx *absdk.Context, cfg Config) error {
		return nil
	},
)
`), 0o644); err != nil {
		t.Fatal(err)
	}

	botDir := filepath.Join(dir, "bot")
	if _, err := AddPluginModule(AddPluginOptions{Dir: botDir, Name: "daily_weather", Module: "example.com/weather"}); err != nil {
		t.Fatal(err)
	}
	runGo(t, botDir, "mod", "edit", "-replace", "github.com/tty00a381/anybot="+root)
	runGo(t, botDir, "mod", "edit", "-replace", "example.com/weather="+pluginDir)
	runGo(t, botDir, "mod", "tidy")
	runGo(t, botDir, "build", "-o", "anybot-bot", ".")
	if err := os.WriteFile(filepath.Join(botDir, "anybot.yaml"), []byte(`plugin_config_dir: plugins.d
plugins: {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	out := runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "enable", "daily_weather")
	if !strings.Contains(out, "插件已启用：daily_weather") ||
		!strings.Contains(out, "默认配置已同步：1 项更新") {
		t.Fatalf("plugin enable:\n%s", out)
	}
	pluginConfig := readFile(t, filepath.Join(botDir, "plugins.d", "daily_weather.yaml"))
	if !strings.Contains(pluginConfig, "enabled: true") ||
		!strings.Contains(pluginConfig, "command: weather") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out = runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "status")
	if !strings.Contains(out, "daily_weather\t外部\t是\t是\t是\t1.0.0\texample.com/weather") {
		t.Fatalf("plugin status:\n%s", out)
	}
	out = runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "check")
	if !strings.Contains(out, "daily_weather\t外部\t可用\t-") {
		t.Fatalf("plugin check:\n%s", out)
	}
	out = runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "inspect", "daily_weather")
	if !strings.Contains(out, "名称：daily_weather") ||
		!strings.Contains(out, "默认配置：") ||
		!strings.Contains(out, "command: weather") {
		t.Fatalf("plugin inspect:\n%s", out)
	}
	out = runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "config", "daily_weather", "command=forecast")
	if !strings.Contains(out, "插件配置已更新：daily_weather") {
		t.Fatalf("plugin config:\n%s", out)
	}
	pluginConfig = readFile(t, filepath.Join(botDir, "plugins.d", "daily_weather.yaml"))
	if !strings.Contains(pluginConfig, "command: forecast") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out = runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "config", "daily_weather", "-reset", "command")
	if !strings.Contains(out, "插件配置已重置：daily_weather（1 项）") ||
		!strings.Contains(out, "默认配置已同步：1 项更新") {
		t.Fatalf("plugin config reset:\n%s", out)
	}
	pluginConfig = readFile(t, filepath.Join(botDir, "plugins.d", "daily_weather.yaml"))
	if !strings.Contains(pluginConfig, "command: weather") || strings.Contains(pluginConfig, "command: forecast") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out = runCommand(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "disable", "daily_weather")
	if !strings.Contains(out, "插件已禁用：daily_weather") {
		t.Fatalf("plugin disable:\n%s", out)
	}
	pluginConfig = readFile(t, filepath.Join(botDir, "plugins.d", "daily_weather.yaml"))
	if !strings.Contains(pluginConfig, "enabled: false") ||
		!strings.Contains(pluginConfig, "command: weather") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out, err = runCommandErr(t, botDir, filepath.Join(botDir, "anybot-bot"), "plugin", "config", "weathre", "command=bad")
	if err == nil {
		t.Fatal("unknown plugin config should fail")
	}
	if !strings.Contains(out, `未知插件 "weathre"`) {
		t.Fatalf("plugin config error:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(botDir, "plugins.d", "weathre.yaml")); !os.IsNotExist(err) {
		t.Fatalf("unknown plugin config should not be created: %v", err)
	}
}

func TestGeneratedPluginLockBuildsStarterPlugin(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	name := "buddy"
	module := "example.com/anybot-buddy"
	wantConfig := []string{
		"command: buddy",
	}
	pluginDir := filepath.Join(dir, name)
	result, err := scaffold.NewPlugin(scaffold.PluginOptions{
		Dir:           pluginDir,
		Name:          name,
		Module:        module,
		AnyBotVersion: "v0.0.0",
		AnyBotReplace: root,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Name != name || !result.Standalone {
		t.Fatalf("plugin result = %#v", result)
	}

	botDir := filepath.Join(dir, "bot")
	if _, err := AddPluginModule(AddPluginOptions{Dir: botDir, Name: name, Module: module}); err != nil {
		t.Fatal(err)
	}
	runGo(t, botDir, "mod", "edit", "-replace", "github.com/tty00a381/anybot="+root)
	runGo(t, botDir, "mod", "edit", "-replace", module+"="+pluginDir)
	runGo(t, botDir, "mod", "tidy")
	runGo(t, botDir, "build", "-o", "anybot-bot", ".")
	if err := os.WriteFile(filepath.Join(botDir, "anybot.yaml"), []byte(`plugin_config_dir: plugins.d
plugins: {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	binary := filepath.Join(botDir, "anybot-bot")
	out := runCommand(t, botDir, binary, "plugin", "enable", name)
	if !strings.Contains(out, "插件已启用："+name) {
		t.Fatalf("plugin enable %s:\n%s", name, out)
	}
	pluginConfig := readFile(t, filepath.Join(botDir, "plugins.d", name+".yaml"))
	if !strings.Contains(pluginConfig, "enabled: true") {
		t.Fatalf("plugin config %s:\n%s", name, pluginConfig)
	}
	for _, want := range wantConfig {
		if !strings.Contains(pluginConfig, want) {
			t.Fatalf("plugin config %s missing %q:\n%s", name, want, pluginConfig)
		}
	}
	out = runCommand(t, botDir, binary, "plugin", "check")
	if !strings.Contains(out, name+"\t外部\t可用\t-") {
		t.Fatalf("plugin check %s:\n%s", name, out)
	}
	out = runCommand(t, botDir, binary, "plugin", "inspect", name)
	if !strings.Contains(out, "名称："+name) ||
		!strings.Contains(out, "当前配置：") ||
		!strings.Contains(out, "默认配置：") {
		t.Fatalf("plugin inspect %s:\n%s", name, out)
	}
	for _, want := range wantConfig {
		if !strings.Contains(out, want) {
			t.Fatalf("plugin inspect %s missing %q:\n%s", name, want, out)
		}
	}
}

func runGo(t *testing.T, dir string, args ...string) {
	t.Helper()
	runCommand(t, dir, "go", args...)
}

func runCommand(t *testing.T, dir, name string, args ...string) string {
	t.Helper()
	out, err := runCommandErr(t, dir, name, args...)
	if err != nil {
		t.Fatalf("%s %s failed: %v\n%s", name, strings.Join(args, " "), err, out)
	}
	return out
}

func runCommandErr(t *testing.T, dir, name string, args ...string) (string, error) {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
