package host

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tty00a381/anybot/internal/scaffold"
)

func TestAddPluginInstallGeneratesLockAndHost(t *testing.T) {
	dir := t.TempDir()
	lock, err := AddPluginInstall(AddPluginInstallOptions{
		Dir:    dir,
		ID:     testWeatherID,
		Module: "github.com/acme/anybot-weather",
	})
	if err != nil {
		t.Fatal(err)
	}
	if lock.Module != "anybot.local/bot" || len(lock.Plugins) != 1 {
		t.Fatalf("lock = %#v", lock)
	}
	if lock.Plugins[0].ID != testWeatherID {
		t.Fatalf("plugin id = %q", lock.Plugins[0].ID)
	}
	lockText := readFile(t, PluginLockPath(dir))
	if !strings.Contains(lockText, "id: "+testWeatherID) ||
		!strings.Contains(lockText, "module: github.com/acme/anybot-weather") ||
		strings.Contains(lockText, "name:") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if !strings.Contains(generated, "Code generated by anybot") ||
		!strings.Contains(generated, `plugin0 "github.com/acme/anybot-weather"`) ||
		!strings.Contains(generated, `plugin0.Plugin.Factory().WithPluginID("`+testWeatherID+`")`) {
		t.Fatalf("generated:\n%s", generated)
	}
	mainGo := readFile(t, filepath.Join(dir, generatedMain))
	if !strings.Contains(mainGo, "Code generated by anybot") ||
		!strings.Contains(mainGo, "registerGeneratedPlugins(external)") ||
		!strings.Contains(mainGo, `os.Args[1] == "plugin"`) ||
		!strings.Contains(mainGo, "host.RunPluginCommand") ||
		!strings.Contains(mainGo, "host.NewApp") {
		t.Fatalf("main.go:\n%s", mainGo)
	}
	goMod := readFile(t, filepath.Join(dir, "go.mod"))
	if !strings.Contains(goMod, "Code generated by anybot") ||
		!strings.Contains(goMod, "module anybot.local/bot") {
		t.Fatalf("go.mod:\n%s", goMod)
	}
}

func TestAddPluginInstallGeneratesRandomID(t *testing.T) {
	dir := t.TempDir()
	lock, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, Module: "github.com/acme/weather"})
	if err != nil {
		t.Fatal(err)
	}
	if len(lock.Plugins) != 1 {
		t.Fatalf("lock = %#v", lock)
	}
	if err := ValidatePluginID(lock.Plugins[0].ID); err != nil {
		t.Fatalf("generated id = %q: %v", lock.Plugins[0].ID, err)
	}
	if !strings.HasPrefix(lock.Plugins[0].ID, "plg_") {
		t.Fatalf("generated id = %q", lock.Plugins[0].ID)
	}
}

func TestEnsurePluginHostCreatesEmptyHost(t *testing.T) {
	dir := t.TempDir()
	lock, err := EnsurePluginHost(dir)
	if err != nil {
		t.Fatal(err)
	}
	if lock.Module != "anybot.local/bot" || len(lock.Plugins) != 0 {
		t.Fatalf("lock = %#v", lock)
	}
	lockText := readFile(t, PluginLockPath(dir))
	if !strings.Contains(lockText, "module: anybot.local/bot") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if !strings.Contains(generated, "Code generated by anybot") ||
		!strings.Contains(generated, "func registerGeneratedPlugins") {
		t.Fatalf("plugins.gen.go:\n%s", generated)
	}
}

func TestLoadPluginLockAcceptsCustomPath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "plugin-lock.yaml")
	if err := os.WriteFile(path, []byte("module: anybot.local/bot\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	lock, err := LoadPluginLock(path)
	if err != nil {
		t.Fatal(err)
	}
	if lock.Module != "anybot.local/bot" {
		t.Fatalf("lock = %#v", lock)
	}
}

func TestLoadPluginLockValidatesLock(t *testing.T) {
	dir := t.TempDir()
	path := PluginLockPath(dir)
	if err := os.WriteFile(path, []byte(`module: anybot.local/bot
plugins:
  - id: `+testWeatherID+`
    module: github.com/acme/weather
  - id: `+testWeatherID+`
    module: github.com/acme/other
`), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := LoadPluginLock(path)
	if err == nil || !strings.Contains(err.Error(), "plugin id "+testWeatherID+" already exists") {
		t.Fatalf("err = %v", err)
	}
}

func TestAddPluginInstallRejectsInvalidIDBeforeWriting(t *testing.T) {
	dir := t.TempDir()
	_, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: "bad/name", Module: "github.com/acme/weather"})
	if err == nil || !strings.Contains(err.Error(), `plugin id "bad/name" is invalid`) {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(PluginLockPath(dir)); !os.IsNotExist(err) {
		t.Fatalf("lock should not be written: %v", err)
	}
}

func TestAddPluginInstallParsesVersionAndReplace(t *testing.T) {
	dir := t.TempDir()
	lock, err := AddPluginInstall(AddPluginInstallOptions{
		Dir:     dir,
		ID:      testWeatherID,
		Module:  "github.com/acme/weather@v1.2.3",
		Replace: "../weather",
	})
	if err != nil {
		t.Fatal(err)
	}
	item := lock.Plugins[0]
	if item.Module != "github.com/acme/weather" || item.Version != "v1.2.3" || item.Replace != "../weather" {
		t.Fatalf("plugin = %#v", item)
	}
	lockText := readFile(t, PluginLockPath(dir))
	if !strings.Contains(lockText, "version: v1.2.3") ||
		!strings.Contains(lockText, "id: "+testWeatherID) ||
		!strings.Contains(lockText, "replace: ../weather") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if strings.Contains(generated, "@v1.2.3") || !strings.Contains(generated, `plugin0 "github.com/acme/weather"`) {
		t.Fatalf("generated:\n%s", generated)
	}
}

func TestRenderPluginHostUpdatesGeneratedMain(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testWeatherID, Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, generatedMain), []byte(generatedHeader+"\n\npackage main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	lock, err := LoadPluginLock(PluginLockPath(dir))
	if err != nil {
		t.Fatal(err)
	}
	if err := RenderPluginHost(dir, lock); err != nil {
		t.Fatal(err)
	}
	mainGo := readFile(t, filepath.Join(dir, generatedMain))
	if !strings.Contains(mainGo, "Code generated by anybot") ||
		!strings.Contains(mainGo, "host.RunPluginCommand") ||
		!strings.Contains(mainGo, "host.NewApp") {
		t.Fatalf("main.go:\n%s", mainGo)
	}
}

func TestRenderPluginHostRejectsUnmanagedMain(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, generatedMain), []byte("package main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := RenderPluginHost(dir, PluginLock{})
	if err == nil {
		t.Fatal("unmanaged main.go should be rejected")
	}
	if !strings.Contains(err.Error(), "不是 anybot 生成文件") {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, generatedPlugins)); !os.IsNotExist(err) {
		t.Fatalf("plugins.gen.go should not be written after preflight failure: %v", err)
	}
}

func TestRenderPluginHostRejectsUnmanagedGoMod(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/app\n\ngo 1.24\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := RenderPluginHost(dir, PluginLock{})
	if err == nil {
		t.Fatal("unmanaged go.mod should be rejected")
	}
	if !strings.Contains(err.Error(), "不是 anybot 生成的 go.mod") {
		t.Fatalf("err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, generatedPlugins)); !os.IsNotExist(err) {
		t.Fatalf("plugins.gen.go should not be written after preflight failure: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, generatedMain)); !os.IsNotExist(err) {
		t.Fatalf("main.go should not be written after preflight failure: %v", err)
	}
}

func TestRenderPluginHostPreservesGeneratedGoMod(t *testing.T) {
	dir := t.TempDir()
	goMod := generatedHeader + `

module anybot.local/bot

go 1.24

require github.com/acme/weather v1.2.3
`
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := RenderPluginHost(dir, PluginLock{}); err != nil {
		t.Fatal(err)
	}
	updated := readFile(t, filepath.Join(dir, "go.mod"))
	if !strings.Contains(updated, "require github.com/acme/weather v1.2.3") {
		t.Fatalf("go.mod should preserve existing dependency:\n%s", updated)
	}
}

func TestAddPluginInstallRejectsDuplicates(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testWeatherID, Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testMemoryID, Module: "github.com/acme/weather"}); err == nil {
		t.Fatal("duplicate module should be rejected")
	}
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testWeatherID, Module: "github.com/acme/weather2"}); err == nil {
		t.Fatal("duplicate id should be rejected")
	}
}

func TestUpdatePluginInstallUpdatesMetadata(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginInstall(AddPluginInstallOptions{
		Dir:     dir,
		ID:      testWeatherID,
		Module:  "github.com/acme/weather@v1.2.3",
		Replace: "../weather",
	}); err != nil {
		t.Fatal(err)
	}
	updated, lock, changed, err := UpdatePluginInstall(UpdatePluginInstallOptions{
		Dir:          dir,
		ID:           testWeatherID,
		Version:      "v1.3.0",
		SetVersion:   true,
		ClearReplace: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("update should report change")
	}
	if updated.Version != "v1.3.0" || updated.Replace != "" || updated.ID != testWeatherID {
		t.Fatalf("updated = %#v", updated)
	}
	if len(lock.Plugins) != 1 || lock.Plugins[0] != updated {
		t.Fatalf("lock = %#v", lock)
	}
	lockText := readFile(t, PluginLockPath(dir))
	if !strings.Contains(lockText, "version: v1.3.0") ||
		strings.Contains(lockText, "replace:") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if !strings.Contains(generated, `registry.Register(plugin0.Plugin.Factory().WithPluginID("`+testWeatherID+`"))`) {
		t.Fatalf("generated:\n%s", generated)
	}
}

func TestUpdatePluginInstallRejectsInvalidInputs(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testWeatherID, Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, _, _, err := UpdatePluginInstall(UpdatePluginInstallOptions{Dir: dir, ID: testGhostID, SetVersion: true, Version: "v1.0.0"}); err == nil {
		t.Fatal("missing plugin should be rejected")
	}
	if _, _, _, err := UpdatePluginInstall(UpdatePluginInstallOptions{Dir: dir, ID: testWeatherID, SetReplace: true, ClearReplace: true}); err == nil {
		t.Fatal("replace conflict should be rejected")
	}
}

func TestRemovePluginInstallUpdatesLockAndHost(t *testing.T) {
	dir := t.TempDir()
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testWeatherID, Module: "github.com/acme/weather"}); err != nil {
		t.Fatal(err)
	}
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: dir, ID: testMemoryID, Module: "github.com/acme/memory"}); err != nil {
		t.Fatal(err)
	}
	removed, lock, err := RemovePluginInstall(RemovePluginInstallOptions{Dir: dir, ID: testWeatherID})
	if err != nil {
		t.Fatal(err)
	}
	if removed.Module != "github.com/acme/weather" || len(lock.Plugins) != 1 || lock.Plugins[0].ID != testMemoryID {
		t.Fatalf("removed=%#v lock=%#v", removed, lock)
	}
	lockText := readFile(t, PluginLockPath(dir))
	if strings.Contains(lockText, "github.com/acme/weather") || !strings.Contains(lockText, "github.com/acme/memory") {
		t.Fatalf("lockText:\n%s", lockText)
	}
	generated := readFile(t, filepath.Join(dir, generatedPlugins))
	if strings.Contains(generated, "github.com/acme/weather") || !strings.Contains(generated, `plugin0 "github.com/acme/memory"`) {
		t.Fatalf("generated:\n%s", generated)
	}
}

func TestRemovePluginInstallRejectsMissing(t *testing.T) {
	dir := t.TempDir()
	if _, _, err := RemovePluginInstall(RemovePluginInstallOptions{Dir: dir, ID: testGhostID}); err == nil {
		t.Fatal("missing plugin should be rejected")
	}
}

func TestGeneratedPluginLockBuildsLocalPlugin(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	pluginDir := filepath.Join(dir, "weather")
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "go.mod"), []byte(`module example.com/weather

go 1.24

require github.com/tty00a381/anybot v0.0.0
`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "weather.go"), []byte(`package weather

import (
	absdk "github.com/tty00a381/anybot/sdk"
)

type Config struct {
	Command string `+"`yaml:\"command\"`"+`
}

var Plugin = absdk.Define(absdk.Spec[Config]{
	Manifest: absdk.Manifest{Name: "天气", Version: "1.0.0", Description: "天气插件"},
	DefaultConfig: Config{Command: "weather"},
	Setup: func(ctx *absdk.Context, cfg Config) error {
		return nil
	},
})
`), 0o644); err != nil {
		t.Fatal(err)
	}

	botDir := filepath.Join(dir, "bot")
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: botDir, ID: testWeatherID, Module: "example.com/weather"}); err != nil {
		t.Fatal(err)
	}
	runGo(t, botDir, "mod", "edit", "-replace", "github.com/tty00a381/anybot="+root)
	runGo(t, botDir, "mod", "edit", "-replace", "example.com/weather="+pluginDir)
	runGo(t, botDir, "mod", "tidy")
	runGo(t, botDir, "build", "-o", "anybot-bot", ".")
	writeTestConfig(t, ConfigPath(botDir), "adapter:\n  transport:\n    listen: \"127.0.0.1:0\"\n")
	binary := filepath.Join(botDir, "anybot-bot")
	weatherShortID := ShortPluginID(testWeatherID)
	out := runCommand(t, botDir, binary, "plugin", "enable", weatherShortID)
	if !strings.Contains(out, "插件已启用："+testWeatherID) ||
		!strings.Contains(out, "默认配置已同步：1 项更新") {
		t.Fatalf("plugin enable:\n%s", out)
	}
	pluginConfig := readFile(t, filepath.Join(botDir, ConfigDirName, testWeatherID+".yaml"))
	if !strings.Contains(pluginConfig, "enabled: true") ||
		!strings.Contains(pluginConfig, "command: weather") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out = runCommand(t, botDir, binary, "plugin", "status")
	if !strings.Contains(out, weatherShortID+"\t天气\t外部\t是\t是\t是\t1.0.0\texample.com/weather") {
		t.Fatalf("plugin status:\n%s", out)
	}
	out = runCommand(t, botDir, binary, "plugin", "check")
	if !strings.Contains(out, weatherShortID+"\t外部\t可用\t-") {
		t.Fatalf("plugin check:\n%s", out)
	}
	out = runCommand(t, botDir, binary, "plugin", "inspect", weatherShortID)
	if !strings.Contains(out, "ID："+testWeatherID) ||
		!strings.Contains(out, "名称：天气") ||
		!strings.Contains(out, "默认配置：") ||
		!strings.Contains(out, "command: weather") {
		t.Fatalf("plugin inspect:\n%s", out)
	}
	out = runCommand(t, botDir, binary, "plugin", "config", weatherShortID, "command=forecast")
	if !strings.Contains(out, "插件配置已更新："+testWeatherID) {
		t.Fatalf("plugin config:\n%s", out)
	}
	pluginConfig = readFile(t, filepath.Join(botDir, ConfigDirName, testWeatherID+".yaml"))
	if !strings.Contains(pluginConfig, "command: forecast") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out = runCommand(t, botDir, binary, "plugin", "config", weatherShortID, "-reset", "command")
	if !strings.Contains(out, "插件配置已重置："+testWeatherID+"（1 项）") ||
		!strings.Contains(out, "默认配置已同步：1 项更新") {
		t.Fatalf("plugin config reset:\n%s", out)
	}
	pluginConfig = readFile(t, filepath.Join(botDir, ConfigDirName, testWeatherID+".yaml"))
	if !strings.Contains(pluginConfig, "command: weather") || strings.Contains(pluginConfig, "command: forecast") {
		t.Fatalf("plugin config:\n%s", pluginConfig)
	}
	out = runCommand(t, botDir, binary, "plugin", "disable", weatherShortID)
	if !strings.Contains(out, "插件已禁用："+testWeatherID) {
		t.Fatalf("plugin disable:\n%s", out)
	}
}

func TestGeneratedPluginLockBuildsStarterPlugin(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	name := "buddy"
	module := "example.com/anybot-buddy"
	pluginDir := filepath.Join(dir, name)
	result, err := scaffold.NewPlugin(scaffold.PluginOptions{
		Dir:           pluginDir,
		Name:          name,
		Module:        module,
		AnyBotVersion: "v0.0.0",
		AnyBotReplace: root,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Name != name {
		t.Fatalf("plugin result = %#v", result)
	}

	botDir := filepath.Join(dir, "bot")
	if _, err := AddPluginInstall(AddPluginInstallOptions{Dir: botDir, ID: testMemoryID, Module: module}); err != nil {
		t.Fatal(err)
	}
	runGo(t, botDir, "mod", "edit", "-replace", "github.com/tty00a381/anybot="+root)
	runGo(t, botDir, "mod", "edit", "-replace", module+"="+pluginDir)
	runGo(t, botDir, "mod", "tidy")
	runGo(t, botDir, "build", "-o", "anybot-bot", ".")
	writeTestConfig(t, ConfigPath(botDir), "adapter:\n  transport:\n    listen: \"127.0.0.1:0\"\n")
	binary := filepath.Join(botDir, "anybot-bot")
	memoryShortID := ShortPluginID(testMemoryID)
	out := runCommand(t, botDir, binary, "plugin", "enable", memoryShortID)
	if !strings.Contains(out, "插件已启用："+testMemoryID) {
		t.Fatalf("plugin enable %s:\n%s", name, out)
	}
	pluginConfig := readFile(t, filepath.Join(botDir, ConfigDirName, testMemoryID+".yaml"))
	if !strings.Contains(pluginConfig, "enabled: true") ||
		!strings.Contains(pluginConfig, "command: buddy") {
		t.Fatalf("plugin config %s:\n%s", name, pluginConfig)
	}
	out = runCommand(t, botDir, binary, "plugin", "inspect", memoryShortID)
	if !strings.Contains(out, "ID："+testMemoryID) ||
		!strings.Contains(out, "名称："+name) ||
		!strings.Contains(out, "当前配置：") ||
		!strings.Contains(out, "默认配置：") {
		t.Fatalf("plugin inspect %s:\n%s", name, out)
	}
}

func runGo(t *testing.T, dir string, args ...string) {
	t.Helper()
	runCommand(t, dir, "go", args...)
}

func runCommand(t *testing.T, dir, name string, args ...string) string {
	t.Helper()
	out, err := runCommandErr(t, dir, name, args...)
	if err != nil {
		t.Fatalf("%s %s failed: %v\n%s", name, strings.Join(args, " "), err, out)
	}
	return out
}

func runCommandErr(t *testing.T, dir, name string, args ...string) (string, error) {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
