package host

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	absdk "github.com/tty00a381/anybot/sdk"
	modmodule "golang.org/x/mod/module"
)

const (
	// PluginLockFile 是 AnyBot 外部插件锁文件。
	PluginLockFile   = "anybot.lock"
	generatedPlugins = "plugins.gen.go"
	generatedMain    = "main.go"
	generatedHeader  = "// Code generated by anybot; DO NOT EDIT."
)

// PluginLock 描述 anybot.lock 中锁定的外部插件来源。
type PluginLock struct {
	Module  string         `yaml:"module"`
	Plugins []PluginModule `yaml:"plugins"`
}

// PluginModule 描述一个外部插件模块及其导出的 sdk.Definition 变量。
type PluginModule struct {
	Name    string `yaml:"name"`
	ID      string `yaml:"id,omitempty"`
	Module  string `yaml:"module"`
	Version string `yaml:"version,omitempty"`
	Replace string `yaml:"replace,omitempty"`
	Symbol  string `yaml:"symbol"`
}

// AddPluginOptions 描述 anybot plugin add 的插件锁更新参数。
type AddPluginOptions struct {
	Dir     string
	Name    string
	Module  string
	Version string
	Replace string
	Symbol  string
}

// UpdatePluginOptions 描述 anybot plugin update 的插件锁更新参数。
type UpdatePluginOptions struct {
	Dir          string
	Name         string
	Version      string
	Replace      string
	Symbol       string
	SetVersion   bool
	SetReplace   bool
	ClearReplace bool
	SetSymbol    bool
}

// RemovePluginOptions 描述 anybot plugin remove 的插件锁更新参数。
type RemovePluginOptions struct {
	Dir  string
	Name string
}

// EnsurePluginHost 确保目录中存在可构建的插件宿主。
func EnsurePluginHost(dir string) (PluginLock, error) {
	return EnsurePluginHostForce(dir, false)
}

// EnsurePluginHostForce 确保插件宿主存在；force 允许接管同名非生成文件。
func EnsurePluginHostForce(dir string, force bool) (PluginLock, error) {
	if dir == "" {
		dir = "."
	}
	lockPath := filepath.Join(dir, PluginLockFile)
	missing := false
	if _, err := os.Stat(lockPath); errors.Is(err, os.ErrNotExist) {
		missing = true
	} else if err != nil {
		return PluginLock{}, err
	}
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(dir, force); err != nil {
		return PluginLock{}, err
	}
	if missing {
		if err := SavePluginLock(lockPath, lock); err != nil {
			return PluginLock{}, err
		}
	}
	if err := renderPluginHost(dir, lock, force); err != nil {
		return PluginLock{}, err
	}
	return lock, nil
}

// AddPluginModule 把外部插件写入插件锁并重写生成宿主。
func AddPluginModule(opts AddPluginOptions) (PluginLock, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Module == "" {
		return PluginLock{}, fmt.Errorf("plugin module is required")
	}
	module, version, err := ParsePluginModuleSpec(opts.Module)
	if err != nil {
		return PluginLock{}, err
	}
	if opts.Version != "" && version != "" && opts.Version != version {
		return PluginLock{}, fmt.Errorf("plugin version conflict: %s and %s", version, opts.Version)
	}
	if opts.Version == "" {
		opts.Version = version
	}
	opts.Module = module
	if opts.Name == "" {
		opts.Name = DefaultPluginName(opts.Module)
	}
	if err := ValidatePluginName(opts.Name); err != nil {
		return PluginLock{}, err
	}
	if opts.Symbol == "" {
		opts.Symbol = "Plugin"
	}
	if !validExportedIdentifier(opts.Symbol) {
		return PluginLock{}, fmt.Errorf("plugin symbol %q must be an exported Go identifier", opts.Symbol)
	}
	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginLock{}, err
	}
	item := PluginModule{
		Name:    opts.Name,
		ID:      DefaultPluginInstanceID(opts.Module, opts.Symbol),
		Module:  opts.Module,
		Version: opts.Version,
		Replace: strings.TrimSpace(opts.Replace),
		Symbol:  opts.Symbol,
	}
	if err := lock.add(item); err != nil {
		return PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginLock{}, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginLock{}, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginLock{}, err
	}
	return lock, nil
}

// UpdatePluginModule 就地更新外部插件元数据并重写生成文件。
func UpdatePluginModule(opts UpdatePluginOptions) (PluginModule, PluginLock, bool, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Name == "" {
		return PluginModule{}, PluginLock{}, false, fmt.Errorf("plugin name is required")
	}
	if opts.SetReplace && opts.ClearReplace {
		return PluginModule{}, PluginLock{}, false, fmt.Errorf("-replace and -clear-replace cannot be used together")
	}
	if opts.SetSymbol {
		opts.Symbol = strings.TrimSpace(opts.Symbol)
		if opts.Symbol == "" {
			opts.Symbol = "Plugin"
		}
		if !validExportedIdentifier(opts.Symbol) {
			return PluginModule{}, PluginLock{}, false, fmt.Errorf("plugin symbol %q must be an exported Go identifier", opts.Symbol)
		}
	}

	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	index := -1
	for i, item := range lock.Plugins {
		if item.Name == opts.Name {
			index = i
			break
		}
	}
	if index < 0 {
		return PluginModule{}, PluginLock{}, false, fmt.Errorf("plugin %s not found", opts.Name)
	}

	original := lock.Plugins[index]
	updated := original
	if opts.SetVersion {
		updated.Version = strings.TrimSpace(opts.Version)
	}
	if opts.SetReplace {
		updated.Replace = strings.TrimSpace(opts.Replace)
	}
	if opts.ClearReplace {
		updated.Replace = ""
	}
	if opts.SetSymbol {
		updated.Symbol = opts.Symbol
	}
	lock.Plugins[index] = updated
	lock.applyDefaults()
	updated = lock.Plugins[index]
	changed := original != updated
	if !changed {
		return updated, lock, false, nil
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginModule{}, PluginLock{}, false, err
	}
	return updated, lock, true, nil
}

// RemovePluginModule 从插件锁移除外部插件并重写生成宿主。
func RemovePluginModule(opts RemovePluginOptions) (PluginModule, PluginLock, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Name == "" {
		return PluginModule{}, PluginLock{}, fmt.Errorf("plugin name is required")
	}
	lockPath := filepath.Join(opts.Dir, PluginLockFile)
	lock, err := LoadPluginLock(lockPath)
	if err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	removed, err := lock.remove(opts.Name)
	if err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	if err := CheckGeneratedHostWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	if err := SavePluginLock(lockPath, lock); err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	if err := RenderPluginHost(opts.Dir, lock); err != nil {
		return PluginModule{}, PluginLock{}, err
	}
	return removed, lock, nil
}

func (lock *PluginLock) add(item PluginModule) error {
	lock.applyDefaults()
	if err := ValidatePluginModule(item); err != nil {
		return err
	}
	for _, existing := range lock.Plugins {
		if existing.Name == item.Name {
			return fmt.Errorf("plugin %s already exists", item.Name)
		}
		if existing.Module == item.Module {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
	}
	lock.Plugins = append(lock.Plugins, item)
	sort.Slice(lock.Plugins, func(i, j int) bool {
		return lock.Plugins[i].Name < lock.Plugins[j].Name
	})
	return nil
}

func (lock *PluginLock) remove(name string) (PluginModule, error) {
	lock.applyDefaults()
	for i, existing := range lock.Plugins {
		if existing.Name == name {
			lock.Plugins = append(lock.Plugins[:i], lock.Plugins[i+1:]...)
			return existing, nil
		}
	}
	return PluginModule{}, fmt.Errorf("plugin %s not found", name)
}

func (lock *PluginLock) applyDefaults() {
	if lock.Module == "" {
		lock.Module = "anybot.local/bot"
	}
	for i := range lock.Plugins {
		if module, version, err := ParsePluginModuleSpec(lock.Plugins[i].Module); err == nil {
			lock.Plugins[i].Module = module
			if lock.Plugins[i].Version == "" {
				lock.Plugins[i].Version = version
			}
		}
		if lock.Plugins[i].Name == "" {
			lock.Plugins[i].Name = DefaultPluginName(lock.Plugins[i].Module)
		}
		if lock.Plugins[i].Symbol == "" {
			lock.Plugins[i].Symbol = "Plugin"
		}
		if lock.Plugins[i].ID == "" {
			lock.Plugins[i].ID = DefaultPluginInstanceID(lock.Plugins[i].Module, lock.Plugins[i].Symbol)
		}
		lock.Plugins[i].Replace = strings.TrimSpace(lock.Plugins[i].Replace)
	}
}

func defaultPluginLock() PluginLock {
	return PluginLock{Module: "anybot.local/bot"}
}

// DefaultPluginName 返回外部插件模块的默认配置名。
func DefaultPluginName(module string) string {
	if parsed, _, err := ParsePluginModuleSpec(module); err == nil {
		module = parsed
	}
	base := path.Base(strings.TrimRight(pluginNameBasePath(module), "/"))
	base = strings.TrimSuffix(base, ".git")
	base = strings.ToLower(base)
	var b strings.Builder
	lastSep := false
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			lastSep = false
		case r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
			lastSep = false
		default:
			if b.Len() > 0 && !lastSep {
				b.WriteByte('_')
				lastSep = true
			}
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "plugin"
	}
	return out
}

// DefaultPluginInstanceID 返回外部插件默认的稳定实例 ID。
func DefaultPluginInstanceID(module, symbol string) string {
	if parsed, _, err := ParsePluginModuleSpec(module); err == nil {
		module = parsed
	}
	if symbol == "" {
		symbol = "Plugin"
	}
	base := DefaultPluginName(module)
	sum := sha256.Sum256([]byte(module + "#" + symbol))
	return base + "_" + hex.EncodeToString(sum[:])[:8]
}

func pluginNameBasePath(module string) string {
	prefix, pathMajor, ok := modmodule.SplitPathVersion(module)
	if !ok || pathMajor == "" || prefix == "" {
		return module
	}
	return prefix
}

// ValidatePluginLock 校验外部插件锁是否可生成稳定 Go 代码。
func ValidatePluginLock(lock PluginLock) error {
	lock.applyDefaults()
	seenNames := map[string]struct{}{}
	seenIDs := map[string]struct{}{}
	seenModules := map[string]struct{}{}
	for _, item := range lock.Plugins {
		if err := ValidatePluginModule(item); err != nil {
			return err
		}
		if _, exists := seenNames[item.Name]; exists {
			return fmt.Errorf("plugin %s already exists", item.Name)
		}
		seenNames[item.Name] = struct{}{}
		if _, exists := seenIDs[item.ID]; exists {
			return fmt.Errorf("plugin id %s already exists", item.ID)
		}
		seenIDs[item.ID] = struct{}{}
		if _, exists := seenModules[item.Module]; exists {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
		seenModules[item.Module] = struct{}{}
	}
	return nil
}

// ValidatePluginModule 校验单个外部插件模块元数据。
func ValidatePluginModule(item PluginModule) error {
	if err := ValidatePluginName(item.Name); err != nil {
		return err
	}
	if item.Module == "" {
		return fmt.Errorf("plugin module is required")
	}
	if err := modmodule.CheckPath(item.Module); err != nil {
		return fmt.Errorf("plugin module %q is invalid: %w", item.Module, err)
	}
	if item.Version != "" {
		if err := modmodule.Check(item.Module, item.Version); err != nil {
			return fmt.Errorf("plugin version %q is invalid for %s: %w", item.Version, item.Module, err)
		}
	}
	if item.Symbol == "" {
		return fmt.Errorf("plugin symbol is required")
	}
	if !validExportedIdentifier(item.Symbol) {
		return fmt.Errorf("plugin symbol %q must be an exported Go identifier", item.Symbol)
	}
	if item.ID == "" {
		item.ID = DefaultPluginInstanceID(item.Module, item.Symbol)
	}
	if err := ValidatePluginName(item.ID); err != nil {
		return fmt.Errorf("plugin id %q is invalid: %w", item.ID, err)
	}
	return nil
}

// ValidatePluginName 校验插件名能安全用于配置名、文件名和实例 ID。
func ValidatePluginName(name string) error {
	return absdk.ValidatePluginName(name)
}

// ParsePluginModuleSpec 解析 module 或 module@version 形式的插件来源。
func ParsePluginModuleSpec(spec string) (module string, version string, err error) {
	spec = strings.TrimSpace(spec)
	if spec == "" {
		return "", "", fmt.Errorf("plugin module is required")
	}
	at := strings.LastIndex(spec, "@")
	if at < 0 {
		return spec, "", nil
	}
	module = strings.TrimSpace(spec[:at])
	version = strings.TrimSpace(spec[at+1:])
	if module == "" || version == "" {
		return "", "", fmt.Errorf("plugin module %q must be module@version", spec)
	}
	return module, version, nil
}

func validExportedIdentifier(name string) bool {
	return token.IsIdentifier(name) && ast.IsExported(name)
}
