package host

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// RenderPluginWorkspace 重写外部插件注册代码，并在缺失时创建最小框架 main.go 和 go.mod。
func RenderPluginWorkspace(dir string, workspace PluginWorkspace) error {
	return renderPluginWorkspace(dir, workspace, false)
}

func renderPluginWorkspace(dir string, workspace PluginWorkspace, force bool) error {
	if dir == "" {
		dir = "."
	}
	workspace.applyDefaults()
	if err := ValidatePluginWorkspace(workspace); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := CheckPluginWorkspaceWritable(dir, force); err != nil {
		return err
	}
	if err := writeGenerated(filepath.Join(dir, generatedPlugins), renderPlugins(workspace), force); err != nil {
		return err
	}
	if err := writeGenerated(filepath.Join(dir, generatedMain), renderMain(), force); err != nil {
		return err
	}
	return writeIfMissing(filepath.Join(dir, "go.mod"), "module "+workspace.Module+"\n\ngo 1.24\n")
}

func renderPlugins(workspace PluginWorkspace) string {
	type pluginImport struct {
		Alias  string
		Name   string
		Module string
		Symbol string
	}
	data := struct {
		Plugins []pluginImport
	}{}
	for i, item := range workspace.Plugins {
		data.Plugins = append(data.Plugins, pluginImport{
			Alias:  fmt.Sprintf("plugin%d", i),
			Name:   item.Name,
			Module: item.Module,
			Symbol: item.Symbol,
		})
	}
	return mustFormat(executeTemplate(pluginsTemplate, data))
}

func renderMain() string {
	return mustFormat(executeTemplate(mainTemplate, nil))
}

func executeTemplate(src string, data any) string {
	tpl := template.Must(template.New("workspace").Parse(src))
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		panic(err)
	}
	return buf.String()
}

func mustFormat(src string) string {
	out, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(out)
}

const pluginsTemplate = `// Code generated by anybot; DO NOT EDIT.

package main

import (
	absdk "github.com/tty00a381/anybot/sdk"
	{{- range .Plugins }}
	{{ .Alias }} "{{ .Module }}"
	{{- end }}
)

func registerExternalPlugins(registry absdk.Registry) error {
	{{- range .Plugins }}
	if err := registry.Register({{ .Alias }}.{{ .Symbol }}.Factory().WithName({{ printf "%q" .Name }})); err != nil {
		return err
	}
	{{- end }}
	return nil
}
`

const mainTemplate = `// Code generated by anybot; DO NOT EDIT.

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/tty00a381/anybot/app/host"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	registry := host.DefaultRegistry()
	if err := registerExternalPlugins(registry); err != nil {
		log.Fatal(err)
	}
	if len(os.Args) > 1 && os.Args[1] == "plugin" {
		if err := host.RunPluginCommand(host.PluginCommandOptions{
			Args:       os.Args[2:],
			Output:     os.Stdout,
			ConfigPath: "anybot.yaml",
			Registry:   registry,
		}); err != nil {
			log.Fatal(err)
		}
		return
	}

	cfg, err := host.LoadConfig("anybot.yaml")
	if err != nil {
		log.Fatal(err)
	}
	logger, err := host.NewLogger(cfg.Runtime.LogLevel, os.Stderr)
	if err != nil {
		log.Fatal(err)
	}
	app, err := host.NewApp(cfg, registry, logger, host.WithConfigPath("anybot.yaml"), host.WithRuntimeState())
	if err != nil {
		log.Fatal(err)
	}
	if err := app.Run(ctx); err != nil && ctx.Err() == nil {
		log.Fatal(err)
	}
}
`
