package host

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	modmodule "golang.org/x/mod/module"
	"gopkg.in/yaml.v3"
)

const (
	// PluginWorkspaceFile 是 anybot 外部插件工作区清单。
	PluginWorkspaceFile = "anybot.plugins.yaml"
	generatedPlugins    = "plugins.gen.go"
	generatedMain       = "main.go"
	generatedHeader     = "// Code generated by anybot; DO NOT EDIT."
)

// PluginWorkspace 描述一个可由 Go 工具链构建的 anybot 插件宿主工程。
type PluginWorkspace struct {
	Module  string         `yaml:"module"`
	Plugins []PluginModule `yaml:"plugins"`
}

// PluginModule 描述一个外部插件模块及其导出的 sdk.Spec 变量。
type PluginModule struct {
	Name    string `yaml:"name"`
	Module  string `yaml:"module"`
	Version string `yaml:"version,omitempty"`
	Replace string `yaml:"replace,omitempty"`
	Symbol  string `yaml:"symbol"`
}

// AddPluginOptions 描述 anybot plugin add 的工作区更新参数。
type AddPluginOptions struct {
	Dir     string
	Name    string
	Module  string
	Version string
	Replace string
	Symbol  string
}

// UpdatePluginOptions 描述 anybot plugin update 的工作区更新参数。
type UpdatePluginOptions struct {
	Dir          string
	Name         string
	Version      string
	Replace      string
	Symbol       string
	SetVersion   bool
	SetReplace   bool
	ClearReplace bool
	SetSymbol    bool
}

// RemovePluginOptions 描述 anybot plugin remove 的工作区更新参数。
type RemovePluginOptions struct {
	Dir  string
	Name string
}

// EnsurePluginWorkspace 确保目录中存在可构建的 anybot 插件宿主工程。
func EnsurePluginWorkspace(dir string) (PluginWorkspace, error) {
	return EnsurePluginWorkspaceForce(dir, false)
}

// EnsurePluginWorkspaceForce 确保插件工作区存在；force 允许接管同名非生成文件。
func EnsurePluginWorkspaceForce(dir string, force bool) (PluginWorkspace, error) {
	if dir == "" {
		dir = "."
	}
	workspacePath := filepath.Join(dir, PluginWorkspaceFile)
	missing := false
	if _, err := os.Stat(workspacePath); errors.Is(err, os.ErrNotExist) {
		missing = true
	} else if err != nil {
		return PluginWorkspace{}, err
	}
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginWorkspace{}, err
	}
	if err := CheckPluginWorkspaceWritable(dir, force); err != nil {
		return PluginWorkspace{}, err
	}
	if missing {
		if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
			return PluginWorkspace{}, err
		}
	}
	if err := renderPluginWorkspace(dir, workspace, force); err != nil {
		return PluginWorkspace{}, err
	}
	return workspace, nil
}

// AddPluginModule 把外部插件加入工作区并重写生成文件。
func AddPluginModule(opts AddPluginOptions) (PluginWorkspace, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Module == "" {
		return PluginWorkspace{}, fmt.Errorf("plugin module is required")
	}
	module, version, err := ParsePluginModuleSpec(opts.Module)
	if err != nil {
		return PluginWorkspace{}, err
	}
	if opts.Version != "" && version != "" && opts.Version != version {
		return PluginWorkspace{}, fmt.Errorf("plugin version conflict: %s and %s", version, opts.Version)
	}
	if opts.Version == "" {
		opts.Version = version
	}
	opts.Module = module
	if opts.Name == "" {
		opts.Name = DefaultPluginName(opts.Module)
	}
	if opts.Symbol == "" {
		opts.Symbol = "Module"
	}
	if !validExportedIdentifier(opts.Symbol) {
		return PluginWorkspace{}, fmt.Errorf("plugin symbol %q must be an exported Go identifier", opts.Symbol)
	}
	workspacePath := filepath.Join(opts.Dir, PluginWorkspaceFile)
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginWorkspace{}, err
	}
	item := PluginModule{Name: opts.Name, Module: opts.Module, Version: opts.Version, Replace: strings.TrimSpace(opts.Replace), Symbol: opts.Symbol}
	if err := workspace.add(item); err != nil {
		return PluginWorkspace{}, err
	}
	if err := CheckPluginWorkspaceWritable(opts.Dir, false); err != nil {
		return PluginWorkspace{}, err
	}
	if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
		return PluginWorkspace{}, err
	}
	if err := RenderPluginWorkspace(opts.Dir, workspace); err != nil {
		return PluginWorkspace{}, err
	}
	return workspace, nil
}

// UpdatePluginModule 就地更新外部插件元数据并重写生成文件。
func UpdatePluginModule(opts UpdatePluginOptions) (PluginModule, PluginWorkspace, bool, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Name == "" {
		return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("plugin name is required")
	}
	if opts.SetReplace && opts.ClearReplace {
		return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("-replace and -clear-replace cannot be used together")
	}
	if opts.SetSymbol {
		opts.Symbol = strings.TrimSpace(opts.Symbol)
		if opts.Symbol == "" {
			opts.Symbol = "Module"
		}
		if !validExportedIdentifier(opts.Symbol) {
			return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("plugin symbol %q must be an exported Go identifier", opts.Symbol)
		}
	}

	workspacePath := filepath.Join(opts.Dir, PluginWorkspaceFile)
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	index := -1
	for i, item := range workspace.Plugins {
		if item.Name == opts.Name {
			index = i
			break
		}
	}
	if index < 0 {
		return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("plugin %s not found", opts.Name)
	}

	original := workspace.Plugins[index]
	updated := original
	if opts.SetVersion {
		updated.Version = strings.TrimSpace(opts.Version)
	}
	if opts.SetReplace {
		updated.Replace = strings.TrimSpace(opts.Replace)
	}
	if opts.ClearReplace {
		updated.Replace = ""
	}
	if opts.SetSymbol {
		updated.Symbol = opts.Symbol
	}
	workspace.Plugins[index] = updated
	workspace.applyDefaults()
	updated = workspace.Plugins[index]
	changed := original != updated
	if !changed {
		return updated, workspace, false, nil
	}
	if err := CheckPluginWorkspaceWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	if err := RenderPluginWorkspace(opts.Dir, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	return updated, workspace, true, nil
}

// RemovePluginModule 从工作区移除外部插件并重写生成文件。
func RemovePluginModule(opts RemovePluginOptions) (PluginModule, PluginWorkspace, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Name == "" {
		return PluginModule{}, PluginWorkspace{}, fmt.Errorf("plugin name is required")
	}
	workspacePath := filepath.Join(opts.Dir, PluginWorkspaceFile)
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	removed, err := workspace.remove(opts.Name)
	if err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	if err := CheckPluginWorkspaceWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	if err := RenderPluginWorkspace(opts.Dir, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	return removed, workspace, nil
}

// LoadPluginWorkspace 读取外部插件工作区清单；文件不存在时返回空工作区。
func LoadPluginWorkspace(path string) (PluginWorkspace, error) {
	if path == "" {
		path = PluginWorkspaceFile
	}
	if err := requireYAMLFile(path, "插件工作区清单"); err != nil {
		return PluginWorkspace{}, err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return defaultPluginWorkspace(), nil
	}
	if err != nil {
		return PluginWorkspace{}, err
	}
	var workspace PluginWorkspace
	if err := yaml.Unmarshal(data, &workspace); err != nil {
		return PluginWorkspace{}, err
	}
	workspace.applyDefaults()
	return workspace, nil
}

// SavePluginWorkspace 写入外部插件工作区清单。
func SavePluginWorkspace(path string, workspace PluginWorkspace) error {
	if path == "" {
		path = PluginWorkspaceFile
	}
	if err := requireYAMLFile(path, "插件工作区清单"); err != nil {
		return err
	}
	workspace.applyDefaults()
	data, err := yaml.Marshal(workspace)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

// RenderPluginWorkspace 重写外部插件注册代码，并在缺失时创建最小宿主 main.go 和 go.mod。
func RenderPluginWorkspace(dir string, workspace PluginWorkspace) error {
	return renderPluginWorkspace(dir, workspace, false)
}

func renderPluginWorkspace(dir string, workspace PluginWorkspace, force bool) error {
	if dir == "" {
		dir = "."
	}
	workspace.applyDefaults()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := CheckPluginWorkspaceWritable(dir, force); err != nil {
		return err
	}
	if err := writeGenerated(filepath.Join(dir, generatedPlugins), renderPlugins(workspace), force); err != nil {
		return err
	}
	if err := writeGenerated(filepath.Join(dir, generatedMain), renderMain(), force); err != nil {
		return err
	}
	return writeIfMissing(filepath.Join(dir, "go.mod"), "module "+workspace.Module+"\n\ngo 1.24\n")
}

// CheckPluginWorkspaceWritable 检查 anybot 生成文件是否可安全写入。
func CheckPluginWorkspaceWritable(dir string, force bool) error {
	if dir == "" {
		dir = "."
	}
	for _, name := range []string{generatedPlugins, generatedMain} {
		if err := checkGeneratedWritable(filepath.Join(dir, name), force); err != nil {
			return err
		}
	}
	return nil
}

func (workspace *PluginWorkspace) add(item PluginModule) error {
	workspace.applyDefaults()
	for _, existing := range workspace.Plugins {
		if existing.Name == item.Name {
			return fmt.Errorf("plugin %s already exists", item.Name)
		}
		if existing.Module == item.Module {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
	}
	workspace.Plugins = append(workspace.Plugins, item)
	sort.Slice(workspace.Plugins, func(i, j int) bool {
		return workspace.Plugins[i].Name < workspace.Plugins[j].Name
	})
	return nil
}

func (workspace *PluginWorkspace) remove(name string) (PluginModule, error) {
	workspace.applyDefaults()
	for i, existing := range workspace.Plugins {
		if existing.Name == name {
			workspace.Plugins = append(workspace.Plugins[:i], workspace.Plugins[i+1:]...)
			return existing, nil
		}
	}
	return PluginModule{}, fmt.Errorf("plugin %s not found", name)
}

func (workspace *PluginWorkspace) applyDefaults() {
	if workspace.Module == "" {
		workspace.Module = "anybot.local/bot"
	}
	for i := range workspace.Plugins {
		if module, version, err := ParsePluginModuleSpec(workspace.Plugins[i].Module); err == nil {
			workspace.Plugins[i].Module = module
			if workspace.Plugins[i].Version == "" {
				workspace.Plugins[i].Version = version
			}
		}
		if workspace.Plugins[i].Name == "" {
			workspace.Plugins[i].Name = DefaultPluginName(workspace.Plugins[i].Module)
		}
		if workspace.Plugins[i].Symbol == "" {
			workspace.Plugins[i].Symbol = "Module"
		}
		workspace.Plugins[i].Replace = strings.TrimSpace(workspace.Plugins[i].Replace)
	}
}

func defaultPluginWorkspace() PluginWorkspace {
	return PluginWorkspace{Module: "anybot.local/bot"}
}

// DefaultPluginName 返回外部插件模块的默认配置名。
func DefaultPluginName(module string) string {
	if parsed, _, err := ParsePluginModuleSpec(module); err == nil {
		module = parsed
	}
	base := path.Base(strings.TrimRight(pluginNameBasePath(module), "/"))
	base = strings.TrimSuffix(base, ".git")
	base = strings.ToLower(base)
	var b strings.Builder
	lastSep := false
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			lastSep = false
		case r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
			lastSep = false
		default:
			if b.Len() > 0 && !lastSep {
				b.WriteByte('_')
				lastSep = true
			}
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "plugin"
	}
	return out
}

func pluginNameBasePath(module string) string {
	prefix, pathMajor, ok := modmodule.SplitPathVersion(module)
	if !ok || pathMajor == "" || prefix == "" {
		return module
	}
	return prefix
}

// ParsePluginModuleSpec 解析 module 或 module@version 形式的插件来源。
func ParsePluginModuleSpec(spec string) (module string, version string, err error) {
	spec = strings.TrimSpace(spec)
	if spec == "" {
		return "", "", fmt.Errorf("plugin module is required")
	}
	at := strings.LastIndex(spec, "@")
	if at < 0 {
		return spec, "", nil
	}
	module = strings.TrimSpace(spec[:at])
	version = strings.TrimSpace(spec[at+1:])
	if module == "" || version == "" {
		return "", "", fmt.Errorf("plugin module %q must be module@version", spec)
	}
	return module, version, nil
}

func renderPlugins(workspace PluginWorkspace) string {
	type pluginImport struct {
		Alias  string
		Name   string
		Module string
		Symbol string
	}
	data := struct {
		Plugins []pluginImport
	}{}
	for i, item := range workspace.Plugins {
		data.Plugins = append(data.Plugins, pluginImport{
			Alias:  fmt.Sprintf("plugin%d", i),
			Name:   item.Name,
			Module: item.Module,
			Symbol: item.Symbol,
		})
	}
	return mustFormat(executeTemplate(pluginsTemplate, data))
}

func renderMain() string {
	return mustFormat(executeTemplate(mainTemplate, nil))
}

func executeTemplate(src string, data any) string {
	tpl := template.Must(template.New("workspace").Parse(src))
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		panic(err)
	}
	return buf.String()
}

func mustFormat(src string) string {
	out, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(out)
}

func writeGenerated(path, content string, force bool) error {
	if err := checkGeneratedWritable(path, force); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func checkGeneratedWritable(path string, force bool) error {
	if force {
		return nil
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if strings.HasPrefix(string(data), generatedHeader) {
		return nil
	}
	return fmt.Errorf("%s 已存在且不是 anybot 生成文件；使用 -force 接管，或换一个空目录", path)
}

func writeIfMissing(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return writeGenerated(path, content, false)
}

func validExportedIdentifier(name string) bool {
	return token.IsIdentifier(name) && ast.IsExported(name)
}

const pluginsTemplate = `// Code generated by anybot; DO NOT EDIT.

package main

import (
	absdk "github.com/tty00a381/anybot/sdk"
	{{- range .Plugins }}
	{{ .Alias }} "{{ .Module }}"
	{{- end }}
)

func registerExternalPlugins(registry absdk.Registry) error {
	{{- range .Plugins }}
	if err := registry.Register({{ .Alias }}.{{ .Symbol }}.Factory().WithName({{ printf "%q" .Name }})); err != nil {
		return err
	}
	{{- end }}
	return nil
}
`

const mainTemplate = `// Code generated by anybot; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/tty00a381/anybot/app/host"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	cfg, err := host.LoadConfig("anybot.yaml")
	if err != nil {
		log.Fatal(err)
	}
	logger, err := host.NewLogger(cfg.Runtime.LogLevel, os.Stderr)
	if err != nil {
		log.Fatal(err)
	}
	registry := host.DefaultRegistry()
	if err := registerExternalPlugins(registry); err != nil {
		log.Fatal(err)
	}
	if len(os.Args) > 1 && os.Args[1] == "plugin" {
		if len(os.Args) < 3 {
			log.Fatal("用法：plugin <sync|status|inspect|config|check|enable|disable>")
		}
		workspace, err := host.LoadPluginWorkspace(host.PluginWorkspaceFile)
		if err != nil {
			log.Fatal(err)
		}
		switch os.Args[2] {
		case "sync":
			result, err := host.SyncPluginConfigEntriesForWorkspace("anybot.yaml", registry, workspace)
			if err != nil {
				log.Fatal(err)
			}
			if err := host.WritePluginConfigSyncSummary(os.Stdout, result); err != nil {
				log.Fatal(err)
			}
		case "status":
			if err := host.WritePluginStatusTable(os.Stdout, host.PluginStatuses(cfg, registry, workspace)); err != nil {
				log.Fatal(err)
			}
		case "inspect":
			if len(os.Args) < 4 {
				log.Fatal("用法：plugin inspect <name>")
			}
			inspect, err := host.InspectPlugin("anybot.yaml", registry, workspace, os.Args[3])
			if err != nil {
				log.Fatal(err)
			}
			if err := host.WritePluginInspect(os.Stdout, inspect); err != nil {
				log.Fatal(err)
			}
		case "config":
			if len(os.Args) < 5 {
				log.Fatal("用法：plugin config <name> <key=value>...，或 plugin config <name> -reset <key>...")
			}
			if err := host.EnsureKnownPluginTarget(cfg, registry, workspace, os.Args[3], true); err != nil {
				log.Fatal(err)
			}
			change, err := host.ParsePluginConfigChanges(os.Args[4:])
			if err != nil {
				log.Fatal(err)
			}
			result, err := host.ApplyPluginConfigChange("anybot.yaml", os.Args[3], change)
			if err != nil {
				log.Fatal(err)
			}
			if result.Reset {
				if result.Changed {
					fmt.Fprintf(os.Stdout, "插件配置已重置：%s（%d 项）\n", os.Args[3], result.Count)
				} else {
					fmt.Fprintf(os.Stdout, "插件配置未变化：%s\n", os.Args[3])
				}
				sync, err := host.SyncPluginConfigEntry("anybot.yaml", registry, os.Args[3])
				if err != nil {
					log.Fatal(err)
				}
				if sync.Changed {
					fmt.Fprintln(os.Stdout, "默认配置已同步：1 项更新")
				} else if !sync.Available {
					fmt.Fprintf(os.Stdout, "默认配置待构建同步：%s（重新运行 anybot up 会完成）\n", os.Args[3])
				}
			} else if result.Changed {
				fmt.Fprintf(os.Stdout, "插件配置已更新：%s（%d 项）\n", os.Args[3], result.Count)
			} else {
				fmt.Fprintf(os.Stdout, "插件配置未变化：%s\n", os.Args[3])
			}
		case "enable", "disable":
			if len(os.Args) < 4 {
				log.Fatalf("用法：plugin %s <name>", os.Args[2])
			}
			enabled := os.Args[2] == "enable"
			name := os.Args[3]
			if err := host.EnsureKnownPluginTarget(cfg, registry, workspace, name, !enabled); err != nil {
				log.Fatal(err)
			}
			changed, err := host.SetPluginEnabled("anybot.yaml", name, enabled)
			if err != nil {
				log.Fatal(err)
			}
			action := "启用"
			if !enabled {
				action = "禁用"
			}
			if changed {
				fmt.Fprintf(os.Stdout, "插件已%s：%s\n", action, name)
			} else {
				fmt.Fprintf(os.Stdout, "插件已处于%s状态：%s\n", action, name)
			}
			if enabled {
				result, err := host.SyncPluginConfigEntry("anybot.yaml", registry, name)
				if err != nil {
					log.Fatal(err)
				}
				if result.Changed {
					fmt.Fprintln(os.Stdout, "默认配置已同步：1 项更新")
				} else if !result.Available {
					fmt.Fprintf(os.Stdout, "默认配置待构建同步：%s（重新运行 anybot up 会完成）\n", name)
				}
			}
		case "check":
			checks := host.PluginConfigChecks(cfg, registry, workspace)
			if err := host.WritePluginConfigCheckTable(os.Stdout, checks); err != nil {
				log.Fatal(err)
			}
			if host.PluginConfigCheckFailed(checks) {
				log.Fatal("插件配置检查失败")
			}
		default:
			log.Fatalf("未知插件命令 %q", os.Args[2])
		}
		return
	}
	app, err := host.NewApp(cfg, registry, logger, host.WithConfigPath("anybot.yaml"), host.WithRuntimeState())
	if err != nil {
		log.Fatal(err)
	}
	if err := app.Run(ctx); err != nil && ctx.Err() == nil {
		log.Fatal(err)
	}
}
`
