package host

import (
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	absdk "github.com/tty00a381/anybot/sdk"
	modmodule "golang.org/x/mod/module"
)

const (
	// PluginWorkspaceFile 是 anybot 外部插件工作区清单。
	PluginWorkspaceFile = "anybot.plugins.yaml"
	generatedPlugins    = "plugins.gen.go"
	generatedMain       = "main.go"
	generatedHeader     = "// Code generated by anybot; DO NOT EDIT."
)

// PluginWorkspace 描述一个可由 Go 工具链构建的 anybot 插件运行框架工程。
type PluginWorkspace struct {
	Module  string         `yaml:"module"`
	Plugins []PluginModule `yaml:"plugins"`
}

// PluginModule 描述一个外部插件模块及其导出的 sdk.Definition 变量。
type PluginModule struct {
	Name    string `yaml:"name"`
	Module  string `yaml:"module"`
	Version string `yaml:"version,omitempty"`
	Replace string `yaml:"replace,omitempty"`
	Symbol  string `yaml:"symbol"`
}

// AddPluginOptions 描述 anybot plugin add 的工作区更新参数。
type AddPluginOptions struct {
	Dir     string
	Name    string
	Module  string
	Version string
	Replace string
	Symbol  string
}

// UpdatePluginOptions 描述 anybot plugin update 的工作区更新参数。
type UpdatePluginOptions struct {
	Dir          string
	Name         string
	Version      string
	Replace      string
	Symbol       string
	SetVersion   bool
	SetReplace   bool
	ClearReplace bool
	SetSymbol    bool
}

// RemovePluginOptions 描述 anybot plugin remove 的工作区更新参数。
type RemovePluginOptions struct {
	Dir  string
	Name string
}

// EnsurePluginWorkspace 确保目录中存在可构建的 anybot 插件运行框架工程。
func EnsurePluginWorkspace(dir string) (PluginWorkspace, error) {
	return EnsurePluginWorkspaceForce(dir, false)
}

// EnsurePluginWorkspaceForce 确保插件工作区存在；force 允许接管同名非生成文件。
func EnsurePluginWorkspaceForce(dir string, force bool) (PluginWorkspace, error) {
	if dir == "" {
		dir = "."
	}
	workspacePath := filepath.Join(dir, PluginWorkspaceFile)
	missing := false
	if _, err := os.Stat(workspacePath); errors.Is(err, os.ErrNotExist) {
		missing = true
	} else if err != nil {
		return PluginWorkspace{}, err
	}
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginWorkspace{}, err
	}
	if err := CheckPluginWorkspaceWritable(dir, force); err != nil {
		return PluginWorkspace{}, err
	}
	if missing {
		if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
			return PluginWorkspace{}, err
		}
	}
	if err := renderPluginWorkspace(dir, workspace, force); err != nil {
		return PluginWorkspace{}, err
	}
	return workspace, nil
}

// AddPluginModule 把外部插件加入工作区并重写生成文件。
func AddPluginModule(opts AddPluginOptions) (PluginWorkspace, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Module == "" {
		return PluginWorkspace{}, fmt.Errorf("plugin module is required")
	}
	module, version, err := ParsePluginModuleSpec(opts.Module)
	if err != nil {
		return PluginWorkspace{}, err
	}
	if opts.Version != "" && version != "" && opts.Version != version {
		return PluginWorkspace{}, fmt.Errorf("plugin version conflict: %s and %s", version, opts.Version)
	}
	if opts.Version == "" {
		opts.Version = version
	}
	opts.Module = module
	if opts.Name == "" {
		opts.Name = DefaultPluginName(opts.Module)
	}
	if err := ValidatePluginName(opts.Name); err != nil {
		return PluginWorkspace{}, err
	}
	if opts.Symbol == "" {
		opts.Symbol = "Plugin"
	}
	if !validExportedIdentifier(opts.Symbol) {
		return PluginWorkspace{}, fmt.Errorf("plugin symbol %q must be an exported Go identifier", opts.Symbol)
	}
	workspacePath := filepath.Join(opts.Dir, PluginWorkspaceFile)
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginWorkspace{}, err
	}
	item := PluginModule{Name: opts.Name, Module: opts.Module, Version: opts.Version, Replace: strings.TrimSpace(opts.Replace), Symbol: opts.Symbol}
	if err := workspace.add(item); err != nil {
		return PluginWorkspace{}, err
	}
	if err := CheckPluginWorkspaceWritable(opts.Dir, false); err != nil {
		return PluginWorkspace{}, err
	}
	if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
		return PluginWorkspace{}, err
	}
	if err := RenderPluginWorkspace(opts.Dir, workspace); err != nil {
		return PluginWorkspace{}, err
	}
	return workspace, nil
}

// UpdatePluginModule 就地更新外部插件元数据并重写生成文件。
func UpdatePluginModule(opts UpdatePluginOptions) (PluginModule, PluginWorkspace, bool, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Name == "" {
		return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("plugin name is required")
	}
	if opts.SetReplace && opts.ClearReplace {
		return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("-replace and -clear-replace cannot be used together")
	}
	if opts.SetSymbol {
		opts.Symbol = strings.TrimSpace(opts.Symbol)
		if opts.Symbol == "" {
			opts.Symbol = "Plugin"
		}
		if !validExportedIdentifier(opts.Symbol) {
			return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("plugin symbol %q must be an exported Go identifier", opts.Symbol)
		}
	}

	workspacePath := filepath.Join(opts.Dir, PluginWorkspaceFile)
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	index := -1
	for i, item := range workspace.Plugins {
		if item.Name == opts.Name {
			index = i
			break
		}
	}
	if index < 0 {
		return PluginModule{}, PluginWorkspace{}, false, fmt.Errorf("plugin %s not found", opts.Name)
	}

	original := workspace.Plugins[index]
	updated := original
	if opts.SetVersion {
		updated.Version = strings.TrimSpace(opts.Version)
	}
	if opts.SetReplace {
		updated.Replace = strings.TrimSpace(opts.Replace)
	}
	if opts.ClearReplace {
		updated.Replace = ""
	}
	if opts.SetSymbol {
		updated.Symbol = opts.Symbol
	}
	workspace.Plugins[index] = updated
	workspace.applyDefaults()
	updated = workspace.Plugins[index]
	changed := original != updated
	if !changed {
		return updated, workspace, false, nil
	}
	if err := CheckPluginWorkspaceWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	if err := RenderPluginWorkspace(opts.Dir, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, false, err
	}
	return updated, workspace, true, nil
}

// RemovePluginModule 从工作区移除外部插件并重写生成文件。
func RemovePluginModule(opts RemovePluginOptions) (PluginModule, PluginWorkspace, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if opts.Name == "" {
		return PluginModule{}, PluginWorkspace{}, fmt.Errorf("plugin name is required")
	}
	workspacePath := filepath.Join(opts.Dir, PluginWorkspaceFile)
	workspace, err := LoadPluginWorkspace(workspacePath)
	if err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	removed, err := workspace.remove(opts.Name)
	if err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	if err := CheckPluginWorkspaceWritable(opts.Dir, false); err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	if err := SavePluginWorkspace(workspacePath, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	if err := RenderPluginWorkspace(opts.Dir, workspace); err != nil {
		return PluginModule{}, PluginWorkspace{}, err
	}
	return removed, workspace, nil
}

func (workspace *PluginWorkspace) add(item PluginModule) error {
	workspace.applyDefaults()
	if err := ValidatePluginModule(item); err != nil {
		return err
	}
	for _, existing := range workspace.Plugins {
		if existing.Name == item.Name {
			return fmt.Errorf("plugin %s already exists", item.Name)
		}
		if existing.Module == item.Module {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
	}
	workspace.Plugins = append(workspace.Plugins, item)
	sort.Slice(workspace.Plugins, func(i, j int) bool {
		return workspace.Plugins[i].Name < workspace.Plugins[j].Name
	})
	return nil
}

func (workspace *PluginWorkspace) remove(name string) (PluginModule, error) {
	workspace.applyDefaults()
	for i, existing := range workspace.Plugins {
		if existing.Name == name {
			workspace.Plugins = append(workspace.Plugins[:i], workspace.Plugins[i+1:]...)
			return existing, nil
		}
	}
	return PluginModule{}, fmt.Errorf("plugin %s not found", name)
}

func (workspace *PluginWorkspace) applyDefaults() {
	if workspace.Module == "" {
		workspace.Module = "anybot.local/bot"
	}
	for i := range workspace.Plugins {
		if module, version, err := ParsePluginModuleSpec(workspace.Plugins[i].Module); err == nil {
			workspace.Plugins[i].Module = module
			if workspace.Plugins[i].Version == "" {
				workspace.Plugins[i].Version = version
			}
		}
		if workspace.Plugins[i].Name == "" {
			workspace.Plugins[i].Name = DefaultPluginName(workspace.Plugins[i].Module)
		}
		if workspace.Plugins[i].Symbol == "" {
			workspace.Plugins[i].Symbol = "Plugin"
		}
		workspace.Plugins[i].Replace = strings.TrimSpace(workspace.Plugins[i].Replace)
	}
}

func defaultPluginWorkspace() PluginWorkspace {
	return PluginWorkspace{Module: "anybot.local/bot"}
}

// DefaultPluginName 返回外部插件模块的默认配置名。
func DefaultPluginName(module string) string {
	if parsed, _, err := ParsePluginModuleSpec(module); err == nil {
		module = parsed
	}
	base := path.Base(strings.TrimRight(pluginNameBasePath(module), "/"))
	base = strings.TrimSuffix(base, ".git")
	base = strings.ToLower(base)
	var b strings.Builder
	lastSep := false
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			lastSep = false
		case r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
			lastSep = false
		default:
			if b.Len() > 0 && !lastSep {
				b.WriteByte('_')
				lastSep = true
			}
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "plugin"
	}
	return out
}

func pluginNameBasePath(module string) string {
	prefix, pathMajor, ok := modmodule.SplitPathVersion(module)
	if !ok || pathMajor == "" || prefix == "" {
		return module
	}
	return prefix
}

// ValidatePluginWorkspace 校验外部插件工作区清单是否可生成稳定 Go 代码。
func ValidatePluginWorkspace(workspace PluginWorkspace) error {
	workspace.applyDefaults()
	seenNames := map[string]struct{}{}
	seenModules := map[string]struct{}{}
	for _, item := range workspace.Plugins {
		if err := ValidatePluginModule(item); err != nil {
			return err
		}
		if _, exists := seenNames[item.Name]; exists {
			return fmt.Errorf("plugin %s already exists", item.Name)
		}
		seenNames[item.Name] = struct{}{}
		if _, exists := seenModules[item.Module]; exists {
			return fmt.Errorf("plugin module %s already exists", item.Module)
		}
		seenModules[item.Module] = struct{}{}
	}
	return nil
}

// ValidatePluginModule 校验单个外部插件模块元数据。
func ValidatePluginModule(item PluginModule) error {
	if err := ValidatePluginName(item.Name); err != nil {
		return err
	}
	if item.Module == "" {
		return fmt.Errorf("plugin module is required")
	}
	if err := modmodule.CheckPath(item.Module); err != nil {
		return fmt.Errorf("plugin module %q is invalid: %w", item.Module, err)
	}
	if item.Version != "" {
		if err := modmodule.Check(item.Module, item.Version); err != nil {
			return fmt.Errorf("plugin version %q is invalid for %s: %w", item.Version, item.Module, err)
		}
	}
	if item.Symbol == "" {
		return fmt.Errorf("plugin symbol is required")
	}
	if !validExportedIdentifier(item.Symbol) {
		return fmt.Errorf("plugin symbol %q must be an exported Go identifier", item.Symbol)
	}
	return nil
}

// ValidatePluginName 校验插件名能安全用于配置名、文件名和数据目录名。
func ValidatePluginName(name string) error {
	return absdk.ValidatePluginName(name)
}

// ParsePluginModuleSpec 解析 module 或 module@version 形式的插件来源。
func ParsePluginModuleSpec(spec string) (module string, version string, err error) {
	spec = strings.TrimSpace(spec)
	if spec == "" {
		return "", "", fmt.Errorf("plugin module is required")
	}
	at := strings.LastIndex(spec, "@")
	if at < 0 {
		return spec, "", nil
	}
	module = strings.TrimSpace(spec[:at])
	version = strings.TrimSpace(spec[at+1:])
	if module == "" || version == "" {
		return "", "", fmt.Errorf("plugin module %q must be module@version", spec)
	}
	return module, version, nil
}

func validExportedIdentifier(name string) bool {
	return token.IsIdentifier(name) && ast.IsExported(name)
}
